### ISSUE TITLE
Cross-platform hotkeys

### ISSUE THREAD

**Issue by AviKav** [uiua-lang/uiua#10]
Cmd-Z & Cmd-Shift-Z don't work on MacOS but Ctrl-Z & Ctrl-Y do.

Turns out there's actually an event for Undo/Redo:
https://stackoverflow.com/questions/13319723/listen-to-undo-redo-event-in-contenteditable-div

**Comment by AviKav** [comment]
Also Ctrl+Click activates the context menu rather than opening docs in new tab

**Comment by kaikalii** [comment]
> Also Ctrl-Click activates the context menu rather than opening docs in new tab

Is this Mac-specific too?

**Comment by AviKav** [comment]
@kaikalii Yes, sorry. It's a Mac specific thing.

I neglected to note that both issues are on both Safari and Chrome

**Comment by kaikalii** [comment]
I'll try hooking into the specific events rather than specific key presses.

**Comment by kaikalii** [comment]
So, I couldn't get anything to detect the history events.
Instead, I just check the user agent to see if you're on mac, then check the meta key rather than ctrl.
0668dfa47bc70375337cde17cf32e18ca09bed05
Let me know if if works.

**Comment by nskobelevs** [comment]
Can confirm Cmd + <key> work on current site build.

Not sure which parts the Cmd + Shift + Click shortcut are for - works for links like glyphs and stuff if that's the use case

**Comment by kaikalii** [comment]
Cool.
I'll mark this as closed for now.
