### ISSUE TITLE
constant item equality broken

### ISSUE THREAD

**Issue by aspiringLich** [uiua-lang/uiua#103]
The latest release works fine, but currently on the main branch equality of constant items is broken.

```apl
=□"apples" □"oranges" # expected: 0       got: 1
={0 ¯3 49593} {1 1 1} # expected: [0 0 0] got: [1 1 1]
```
this applies to `member` and `find` too and probably other functions as well.

Might want to add a test for this too; I don't think there's one there for this currently.

**Comment by kaikalii** [comment]
Fixed in 6756731ed12b3
