### ISSUE TITLE
`if` can't take a function?

### ISSUE THREAD

**Issue by goyalyashpal** [uiua-lang/uiua#112]
```uiua
# Trying to apply:
# (a % b != 0) ? (a/b) : (a*b)

# IFork ← ?× ⊃(≠0 ◿) ÷|
IFork ← ?×÷(≠0 ◿) ,,
IFork 4 36
```

```
Error: If's condition must be a natural number, but it is function
   ╭─[fork.ua:5:9]
 8 │ IFork ← ?×÷(≠0 ◿) ,,
   │         ─
───╯
  in ?       at fork.ua:5:9
  in `IFork` at fork.ua:6:1
```

**Comment by kaikalii** [comment]
I generally recommend the version you install via `cargo install`.
In this case however, the row-wise `if ?` you are looking for was only recently implemented, and so is only available on `main`.

**Comment by goyalyashpal** [comment]
_self hiding as offtopic_

----
This code throws error mentioning `signatures |2.1 and |2.2`. This format is documented at `[sig]`. 

This is so crucial for the goal in my mind, i was looking for this for so long. combined with `type`

[sig]: https://www.uiua.org/docs/sig

```uiua
IFork ← ?× ⊃(≠0 ◿) ÷
```

```
Error: Cannot infer function signature: if's branches with signatures |2.1 and |2.2 have a different numbers of outputs
   ╭─[:1:1]
 1 │ IFork ← ?× ⊃(≠0 ◿) ÷
   │ ─────  
───╯
```


https://github.com/uiua-lang/uiua/blob/d166fa29fb1b55b5662de79dbd96c4b31933675a/src/primitive/defs.rs#L1457-L1460
https://github.com/uiua-lang/uiua/blob/d166fa29fb1b55b5662de79dbd96c4b31933675a/src/primitive/defs.rs#L1446-L1456

**Comment by goyalyashpal** [comment]
> I generally recommend the version you install via `cargo install`.

so, what should be the updating frequency from there?

**Comment by kaikalii** [comment]
It will tell you when there is a new version available.

**Comment by iFreilicht** [comment]
@goyalyashpal New version 0.0.18 was just released! See https://www.uiua.org/docs/changelog

**Comment by iFreilicht** [comment]
@goyalyashpal, are you happy with the solution? If so, please close the issue :)

**Comment by goyalyashpal** [comment]
hi yeah, last week was busy.

regarding `if`: it's messy. my guess regarding it being an odd-one-out among this stack/array paradigm is correct. but yeah, this issue can be closed,

plain `max * != ... dup` works far better

```uiua
IFork ← ?(⋅∘)(÷) ≠0 ◿ ,,
# IFork ← ↥ ⊃(÷)(× ≠0 ◿) ⊙.

IFork 4 35      # 35
IFork 4 36      # 9
IFork 4 [35 36] # [35 9]
# 😶 Error
```

```log
Error: If's condition must have the same number of rows as 
its arguments, but it has 2 rows and its arguments have 1 and 2 rows
   ╭─[:1:9]
 1 │ IFork ← ?(⋅∘)(÷) ≠0 ◿ ,,
   │         ─  
───╯
  in `IFork` at 6:1
```

**Comment by iFreilicht** [comment]
@goyalyashpal btw, you might want to check out the current pre-release on the website, where [the code you showed above works with minor adjustments](https://uiua.org/pad?src=SUZvcmsg4oaQID_iiJjDtyDiiaAwIOKXvyAsLApJRm9yayA0IDMKSUZvcmsgMiA3CklGb3JrIDQgMzI=):

```
IFork ← ?∘÷ ≠0 ◿ ,,
IFork 4 3
IFork 2 7
IFork 4 32
```

It will be available via cargo soon, see the note in the [changelog](https://www.uiua.org/docs/changelog).

**Comment by goyalyashpal** [comment]
> IFork 4 3   # 4
> IFork 2 7   # 2
> IFork 4 32  # 8

uhm, the fxn i wrote was for `exact_division_or_default` (name suggested by `gpt-3.5-turbo-instruct`); so, 
* `4 3` should give 4 (incorrect above)
* `2 7` should give 7 (incorrect above)
* `4 32` should give 8 (correct above)

**Comment by iFreilicht** [comment]
Ah I see. I'm not sure if Kai wants to implement the pervasiveness that you expected of if, but if you just want a solution, [how about this?](https://www.uiua.org/pad?src=SUZvcmsg4oaQID_ii4XiiJjDtyDiipko4oav4oi24oqZKOKWsy4pKSDiiaAwIOKXvyAsLApJRm9yayA0IDMKSUZvcmsgMiA3CklGb3JrIDQgMzIKSUZvcmsgWzQgNF0gWzM1IDM2XSAjIFszNSA5XQpJRm9yayA0IFszNSAzNl0gICAgICMgWzM1IDld):

```
IFork ← ?⋅∘÷ ⊙(↯∶⊙(△.))
```

**Comment by goyalyashpal** [comment]
> ```uiua
> IFork ← ?⋅∘÷ ⊙(↯∶⊙(△.)) ≠0 ◿ ,,
> ```

thanks a lot for efforts, but why not the code i shared [above](https://github.com/uiua-lang/uiua/issues/112#issuecomment-1762816857)?

```uiua
IFork ← ↥ ⊃(÷)(× ≠0 ◿) ⊙.
```

**Comment by goyalyashpal** [comment]
ohw, it just clicked to me that:
* parenthesis is not an idle/grouping operator in uiua; 
* rather it creates inline functions 
* which have to be called (either implicitly by parent fxn, or explicitly using `!` call

so, the fix for the code in stadting comment is just putting a `call` before the paren.

```uiua
# Trying to apply:
# (a % b != 0) ? (a/b) : (a*b)

# IFork ← ?× ⊃(≠0 ◿) ÷|
IFork ← ?×÷(≠0 ◿) ,,   # Original
IFork ← ?×÷!(≠0 ◿) ,,  # Fixed using !call
IFork 4 36
```

----
references: per the following:

* https://github.com/uiua-lang/uiua/issues/136#issuecomment-1763310051
> _"with if, you can pass it a value that is the result of a another computation."_

* https://github.com/uiua-lang/uiua/blob/a14db387302f97eff7373286df541cc3f60169d0/src/primitive/defs.rs#L1389-L1390

* https://github.com/uiua-lang/uiua/blob/a14db387302f97eff7373286df541cc3f60169d0/site/src/tour.rs#L117-L118

* https://github.com/uiua-lang/uiua/blob/a14db387302f97eff7373286df541cc3f60169d0/src/primitive/defs.rs#L1360-L1363

* `Error: If's condition must be a natural number, but it is function`
