### ISSUE TITLE
Add `\e` escape character

### ISSUE THREAD

**Issue by dosisod** [uiua-lang/uiua#114]
I've been playing around with Uiua for some CLI applications, and I've found that making ANSI escape sequences are a bit hard without having a dedicated `\e` escape sequence.

For example, I have the [following code](https://github.com/dosisod/uordle/blob/b06c8d13066891b3fdca89390081a69621b25cda/uordle.ua#L24-L42):

```
Escape ← + 27 @\0

PrintBanner ← (|0
  ⍥Escape 7
  WordLen
  &p $ uordle: wordle written in uiua.
     $ 
     $ rules:
     $ 
     $ * type words in lower case
     $ * words must be _ characters long
     $ * _[42;30m green  _[0m means correct character is in the right spot
     $ * _[43;30m yellow _[0m means correct character is in the wrong spot
     $ * _[48;5;240m_[30m gray   _[0m means incorrect character
     $ 
     $ type a word to get started
)
```

While this banner is mostly static, I have to inject a bunch of `Escape` values using a format string, which gets hard to manage if I add more escapes later on.

The escape sequence doesn't have to be `\e`, it could be `\x1b` or `\033`, though having a `\xNN` escape sequence would mean you would have 2 ways to make characters (using `+ X @\0` and `"\xNN"`).

What are your thoughts on this? Thanks!

**Comment by iFreilicht** [comment]
I submitted a PR that adds `\e`. Adding arbitrary unicode escape sequences is interesting, but not as useful of a feature (as for those rare cases you can use `+ 1234 @\0` like you showed), and it would make the lexer more complex.

**Comment by kaikalii** [comment]
I have implemented hex character escapes in 065a3bf2a681f3c4cb.
You would now uses something like
```
WordLen
&p $ uordle: wordle written in uiua.
   $ 
   $ rules:
   $ 
   $ * type words in lower case
   $ * words must be _ characters long
   $ * \x1b[42;30m green  \x1b[0m means correct character is in the right spot
   $ * \x1b[43;30m yellow \x1b[0m means correct character is in the wrong spot
   $ * \x1b[48;5;240m\x1b[30m gray   \x1b[0m means incorrect character
   $ 
   $ type a word to get started
```

**Comment by iFreilicht** [comment]
@dosisod, version 0.0.18 has been released a few days ago. It contains the new `\xnn` escape sequence. Can you update and test if this works for you, and if so, close this issue?

**Comment by dosisod** [comment]
Yes it works for me, thanks!
