### ISSUE TITLE
Formatter will unindent lines if they end with a comment if `align_comments` is enabled

### ISSUE THREAD

**Issue by iFreilicht** [uiua-lang/uiua#116]
The snippet below is formatted correctly if there are no comments or the comments are on separate lines, but indentation is reset if there one of the lines ends with a comment

![Screenshot 2023-10-10 at 13 02 34](https://github.com/uiua-lang/uiua/assets/9742635/6dbc7169-241b-46ae-ac19-188d9095950d)
![Screenshot 2023-10-10 at 13 06 40](https://github.com/uiua-lang/uiua/assets/9742635/65baa4b8-0972-49c9-85da-e0a3080aa0ac)
![Screenshot 2023-10-10 at 13 02 58](https://github.com/uiua-lang/uiua/assets/9742635/3a00882f-212d-48b4-b2cc-2b9e91591035)

Setting `AlignComments = 0` in `.fmt.ua` works around this issue.

**Comment by kaikalii** [comment]
Fixed in 4bdace848d
