### ISSUE TITLE
Unexpected behavior with `?` inside functions with explicit signatures

### ISSUE THREAD

**Issue by dosisod** [uiua-lang/uiua#122]
When using `?` in a function with a signature, `?` expects a value even for functions that don't return values:

```
f ← (|1.0 ?(&p "arg is > 0")∘)

f 0
f 1
```

```
Error: Stack was empty when evaluating array argument 1
   ╭─[:1:11]
 1 │ f ← (|1.0 ?(&p "arg is > 0")∘)
   │           ─  
───╯
  in ?   at 1:11
  in `f` at 3:1
```

When removing the `|1.0` signature, you get an error saying that the function signatures differ:

```
Error: Cannot infer function signature: if's branches with signatures |0.0 and |1.1 have a different numbers of outputs
   ╭─[:1:5]
 1 │ f ← (?(&p "arg is > 0")∘)
   │     ─────────────────────  
───╯
```

In short, `∘` used to act as a no-op if `?` returned false, but now it causes an error. Also, `?` in functions with signatures hides the new branch signature checking.

As a workaround I can explicitly return values and discard them, though this is not ideal:

```
f ← (;?(1 &p "arg is > 0")(1))
```

I came across this while doing something unrelated in https://github.com/dosisod/uordle/commit/943646d3ff48a0bcfb6b72406704b2a40be7d91b

**Comment by kaikalii** [comment]
Currently, on `main`, as a workaround, you can do:
```
f ← (?(&p "arg is > 0")(|0.0))
```
I'm not sure what I want to do about this.
I like being able to type `()` for `identity`, but it can create problems like this.
One possible option is to add a special case for `identity`.

**Comment by tomKPZ** [comment]
> Currently, on `main`, as a workaround, you can do:
> 
> ```
> f ← (?(&p "arg is > 0")(|0.0))
> ```
> 
> I'm not sure what I want to do about this. I like being able to type `()` for `identity`, but it can create problems like this. One possible option is to add a special case for `identity`.

I wonder if function signatures can be the difference between the # of args and the # of return values?  So `+` would have signature `|-1` and `.` would have `|+1` and `()` would simply have `|0`.

**Comment by kaikalii** [comment]
There is a lot of value in knowing exactly how many arguments a function takes, not just its stack delta.

**Comment by iFreilicht** [comment]
This has been fixed on main, potentially as a result of fixing #130. The new version is already deployed on the website, so if you [run this code in the pad](https://www.uiua.org/pad?src=ZiDihpAgPygmcCAiYXJnIGlzID4gMCIp4oiYCgpmIDAKZiAx), it does what you expect:

```
f ← ?(&p "arg is > 0")∘

f 0
f 1
```
