### ISSUE TITLE
The docs imply `?` can take any number, but it only takes `0` or `1`

### ISSUE THREAD

**Issue by dosisod** [uiua-lang/uiua#123]
The docs imply that `?` can take any value, but when running it says it must be `0` or `1`:

![image](https://github.com/uiua-lang/uiua/assets/39638017/bb86d96d-892e-4456-a8a0-694632cc9365)

Also, are these docs for the website on GitHub? I'd update it myself but I don't know where the docs/website are, assuming they are public.

**Comment by kaikalii** [comment]
Fixed in 699c68a04eb18863

**Comment by goyalyashpal** [comment]
> Fixed in [699c68a](https://github.com/uiua-lang/uiua/commit/699c68a04eb18863ef49d40cd98ab4c80371107f)

Clarification: fixed in docs
