### ISSUE TITLE
Recur inside each refuses to infer

### ISSUE THREAD

**Issue by Bubbler-4** [uiua-lang/uiua#125]
Example: https://www.uiua.org/pad?src=ZiDihpAgfDEgLyviiLUo4oasMinih6EKCmYgMg==

```
f ← |1 /+∵(↬2)⇡
```

This function is meant to take a positive integer, recurse over each number in the range, and then sum the result. Clearly the arity of this function is `1.1`. However, the interpreter rejects the definition whatever argument I give to `↬`. I think 2 is the right value there?

**Comment by Bubbler-4** [comment]
Hmm, so I need to annotate the *immediate enclosing function*. `(|1 ↬2)` seems to work. Maybe having a similar example in the docs would be helpful.

**Comment by kaikalii** [comment]
This one is in the [docs for `recur`](https://www.uiua.org/docs/recur):
```
!(?∘(|1 +↬2-1∶↬2-2.) <2.) 10
```
