### ISSUE TITLE
Did anyone manage to use it with Emacs?

### ISSUE THREAD

**Issue by bortzmeyer** [uiua-lang/uiua#13]
I try to use Emacs as an editor. To have Emacs automatically reload the file, I add:

```
(global-auto-revert-mode t)
```

When Emacs saves the file, it actually creates a new file which makes uiua miss it and display "failed to load /home/stephane/tmp/uiua/main.ua: No such file or directory (os error 2)". So, I tell Emacs not to make backup files, thus overwriting the file instead of creating a new one:

```
(setq make-backup-files '())
```

Now, uiua no longer complains, Emacs reloads the file if it is changed by an external program (I tested with vi and with `uiua fmt`) *but* not when it was changed by used uiua interactively: Emacs continues to display the old file, even when uiua changed it.

**Comment by bortzmeyer** [comment]
In the mean time, calling `uiua fmt main.ua`  and `uiua run main.ua` from inside Emacs produces the expected result and may form the basis of a simple "uiua mode".

**Comment by emiflake** [comment]
I'd love to help here too. Facilities such as running the line you're on and displaying it would be great, especially with image support.

**Comment by kaikalii** [comment]
I use VSCode, so that is what I test the language server with.
Unfortunately, I can't get VSCode to request stuff like semantic tokens or inlay values from the server, so I'm unable to test it there.

**Comment by crmsnbleyd** [comment]
https://github.com/crmsnbleyd/uiua-mode, initiated a repository, I'll start hacking. I'm on the uiua discord as well, under @crmsnbleyd if anyone wants to collaborate there

**Comment by crmsnbleyd** [comment]
uiua-ts-mode is now on [melpa](https://melpa.org/#/uiua-ts-mode), if you all are interested.

cc @emiflake @bortzmeyer

**Comment by kaikalii** [comment]
> https://github.com/crmsnbleyd/uiua-mode, initiated a repository, I'll start hacking. I'm on the uiua discord as well, under @crmsnbleyd if anyone wants to collaborate there

I've linked to this on the [install page](https://www.uiua.org/install#editor-support).
