### ISSUE TITLE
haskell `[x:xs]` as first/drop or take/drop combo ?

### ISSUE THREAD

**Issue by goyalyashpal** [uiua-lang/uiua#131]
### Titles
* combination of `↙Take` and `↘Drop` as `⤩`??
* haskell `[x:xs]` as first/drop or take/drop combo

#### from haskell

* Haskell provide a  convenient way to partition an input array into `[head : tail]` aka `[x:xs]` where head is the first element & tail refers to remaining
* This comes super handy when thinking about algo at higher level

For example, here's how i easily visualised about an algo using this feature:

```haskell
-- Pseudocode
-- lcmn (1..n)
lcmn [x:xs] = x * lcmn (xs ★ x)

-- ★ would a custom function
```

#### from Uiua

* Doing same (i.e. `[x:xs]` in Uiua requires using `⊃` fork, which adds some clutter to the code.

```uiua
# 2023-10-14 23:48:19
# haskell-head-tail.ua
# uiua v0.0.18

⤩ ← |1.2 ⊃(⊢)(↘1) # 2 [3 4 5 6 7]
⤩ ← |2.2 ⊃(↙)(↘)  # [2] [3 4 5 6 7]

⤩1 +2 ⇡6
```

### Discussion
* So, do you think that this is common enough to warrant the need for a dedicated built-in?
* if yes, then will the generic one with `|2.2` which has to specify where to part, or the hard coded `|1.2` one which partitions always at one?

some more experimentation in code:

```uiua
# 2023-10-14 23:48:19
# haskell-head-tail.ua

HtOne ← |1.2 ⊃(⊢)(↘1)
HtGnr ← |2.2 ⊃(↙)(↘)

# HtOne ⇡6   # 0 [1 2 3 4 5]
# HtGnr 1 ⇡6 # [0] [1 2 3 4 5]

# HtOne ⇡1   # 0 []
# HtGnr 1 ⇡1 # [0] []
# HtGnr 0 ⇡1 # [] [0]

# HtOne ⇡0 # Can't take first of an empty array
HtGnr 0 ⇡0 # [] []
```

### Addendum

<details><summary>Full haskell code</summary>

You may use [OneCompiler] to try this Haskell code online.

[OneCompiler]: https://onecompiler.com/haskell "Haskell on OneCompiler"

```haskell
-- Function Definitions
lcmn :: [Integer] -> Integer
lcmn [x] = x
lcmn (x:xs) = x * (lcmn (map (div_or_def x) xs))

div_or_def :: Integer -> Integer -> Integer
div_or_def y x = if mod x y == 0 then div x y else x

-- Main
main :: IO()
main = do
  print (map (div_or_def 3) [1..6]) -- [1,2,1,4,5,2]
  print (lcmn [1..10])              -- 2520
```

</details>

**Comment by kaikalii** [comment]
I think these are [easy enough to write](https://uiua.org/pad?src=4oqD4oaZ4oaYIDIgWzEgMiAzIDQgNV0K4oqD4oqiJ-KGmDEgWzEgMiAzIDQgNV0=) without the need for a builtin.

**Comment by goyalyashpal** [comment]
> [easy enough to write](https://uiua.org/pad?src=4oqD4oaZ4oaYIDIgWzEgMiAzIDQgNV0K4oqD4oqiJ-KGmDEgWzEgMiAzIDQgNV0=)

ahhww, that's what [bind] does - binds or say clubs two consecutive things together without requiring parenthesis. lol, nice syntactic sugar :)

[bind]: https://www.uiua.org/docs/bind

> This modifier mostly exists for syntactic convenience
> \- [bind] at uiua.org/docs
