### ISSUE TITLE
type aware signature?? (sig querying functions & sig declaring annotations)

### ISSUE THREAD

**Issue by goyalyashpal** [uiua-lang/uiua#132]
* the <tt>[sig] (fn)</tt> builtin function is awesome for getting/querying the numeric signature
* the `|#.#` [signature annotation] is awesome for specifying/declaring the numeric signature (though it lacks documentation)

but 
* is there any way to specify or at least query the typed signature? 
* ... or in the plans? 
* ... even just for builtin functions for the time being?

typed as in: 
* scalar (number), 
* array, 
* string, 
* stack function, 
* function

[sig]: https://uiua.org/docs/sig
[signature annotation]:  https://www.uiua.org/docs/recur#:~:text=annotated%20with%20a%20signature "mentioned in ↬ recur"

**Comment by kaikalii** [comment]
I have though and even tried to start implementing a type/shape checker.
The problem is that it would require basically making a separate implementation of every function that operates on types and shapes rather than values, since the output type/shape of a function depends on its inputs.

**Comment by goyalyashpal** [comment]
> since the output type/shape of a function depends on its inputs.

my scope is not about outputs, rather just about inputs i.e. what inputs a function takes.

as the output is, as you very well noted, can become complex; generally not of my concern so far for other than plain values on stack

**Comment by kaikalii** [comment]
What would the type of, say, `+` be?

**Comment by goyalyashpal** [comment]
> What would the type of, say, `+` be?

scalar scalar

**Comment by kaikalii** [comment]
But that's not what it is. It is rank-polymorphic.

**Comment by goyalyashpal** [comment]
the rank polymorphism can be inferred by the reader - sort of like type promotion
that is, if all rank polymorphisms here are consistent (which i think they are)

i am thinking on the lines of: specify the minimum applicable thing

**Comment by kaikalii** [comment]
Okay. No, I don't think I'll add this.

**Comment by goyalyashpal** [comment]
ohkay. but can there be some documentation about the current type hierarchy at least?

that is, documentation regarding what are the various semantic types in uiua-lang?

**Comment by kaikalii** [comment]
There is an entire [part of the tutorial](https://www.uiua.org/docs/types) about types.
Also, the documentation for each function says whether it is pervasive.
