### ISSUE TITLE
Support fill for first

### ISSUE THREAD

**Issue by iFreilicht** [uiua-lang/uiua#133]
Right now, fill [seems to work for `pick 0`, but not `first`](https://uiua.org/pad?src=4qyaMeKKoTDiipogMF8wXzAK4qyaMeKKouKKmiAwXzBfMA==):

```
⬚1⊡0⊚ 0_0_0 # Returns 1
⬚1⊢⊚ 0_0_0  # Error: Cannot take first of an empty array 
```

It would be nice if it did.

**Comment by kaikalii** [comment]
Good idea.
I'm not sure why I hadn't already implemented that.
Added in 0c5da8e9dcee6

**Comment by iFreilicht** [comment]
Tested it, seems to work as intended.
