### ISSUE TITLE
`&about` system function on uiua pad web?

### ISSUE THREAD

**Issue by goyalyashpal** [uiua-lang/uiua#135]
currently there seems to be no direct way to know the running version of uiua on uiua-pad online. 

so, i was thinking that maybe having a system function i.e. smth like `&about` or `&ver` may help in those cases.

though this doesnt need to be a lang's function & there can be other ways to tackle this too.

on the other hand, being a lang fxn may provide value at places other than just the website too (ig)

**Comment by kaikalii** [comment]
On native `uiua -V` gives the current version.
On the website, there is the [changelog](https://www.uiua.org/docs/changelog).
I don't see much value in adding it as a system function.

**Comment by goyalyashpal** [comment]
> I don't see much value in adding it as a system function

yeah, i was thinking same.

how about adding a current version ui widget on uiua-pad webpage itself?

**Comment by kaikalii** [comment]
The pad now shows the version number in the link.

**Comment by goyalyashpal** [comment]
example: https://www.uiua.org/pad?src=0_3_1__Mwo=
