### ISSUE TITLE
copy last n values of stack

### ISSUE THREAD

**Issue by goyalyashpal** [uiua-lang/uiua#136]
* this may help in some cases where the `fork` fails

* also, this may provide a better alternate to the `over over` phrase which copies last 2 values on stack

Examples: coming soon

**Comment by kaikalii** [comment]
Parametric stack copying is not something I'd like to encourage.
If you want to copy stack values, you should know exactly how many there are at the time you write your program.
I think `,,` is a fine idiom.
Fork more than 2, `fork` is adequate.

**Comment by goyalyashpal** [comment]
> Parametric stack copying is not something I'd like to encourage.

it can allow only literal value similar to how `if` used to take only `0|1` i.e. v0.0.17

**Comment by kaikalii** [comment]
But with `if`, you can pass it a value that is the result of a another computation.
No Uiua functions currently *require* that their arguments are known at compile time.

**Comment by goyalyashpal** [comment]
> Fork more than 2, `fork` is adequate.

umh, sorry?

**Comment by kaikalii** [comment]
*For* more than 2.
