### ISSUE TITLE
space separation in uiuisms for better readability?

### ISSUE THREAD

**Issue by goyalyashpal** [uiua-lang/uiua#146]
1. I was reading the uiusms on my android running phone; and 
    * uiuism for cross product was very long to the point that it was not fitting on display
    * i put the data (the arguments) on prev line similar to matrix product (the `\n` in code); 

2. but
    * the function part was still unreadable code due to lack of spacing
    * which made me notice that none of the uiusm contain _any_ space whatsoever (other than for predicates)
    * putting space will be of great benefit for readability which is never a bad thing (for both beginners & senior programmers alike)

i would be willing to create a pr addressing both the points if either of these is wanted

----
References:

<img src="https://github.com/uiua-lang/uiua/assets/19423063/015ee0ed-fc19-47ba-ba75-4c088b7245c3" width=250px />

* https://www.uiua.org/isms
https://github.com/uiua-lang/uiua/blob/bd409855f23416b75b6f1db452503fdae8ce17e4/site/src/uiuisms.rs#L206-L211
https://github.com/uiua-lang/uiua/blob/bd409855f23416b75b6f1db452503fdae8ce17e4/site/src/uiuisms.rs#L124-L125

* https://github.com/uiua-lang/uiua/blob/bd409855f23416b75b6f1db452503fdae8ce17e4/site/src/uiuisms.rs#L168-L171

**Comment by kaikalii** [comment]
I think it's okay to break up very long ones into multiple lines.
However, most of the Uiua code I've seen people write is devoid of spaces.
I think it's good for the Uiuisms to have the same style.
I only put spaces before the example arguments so you can distinguish them from the code itself.

**Comment by goyalyashpal** [comment]
> [ppl's uiua code: devoid of space] => [it's good for the Uiuisms to have the same style.]

uiua being a very new language, the same can be took in other direction: uiuisms should set an example of good readable code so that people can take inspiration from that.

also, (i might be wrong here, feel free to correct if so) - i think most ppl are using uiua only for single person or extremely small team at best; at which case ppl have tendency to fall sloppy. uiua official is only place in my knowledge which is used public.

**Comment by kaikalii** [comment]
I think I like the way it is.

**Comment by goyalyashpal** [comment]
i really hope you have change of heart some day 😅😆 

anyhow, thanks for your time 😇
