### ISSUE TITLE
Function suggestions: solo, fold-scan, repeat-collect

### ISSUE THREAD

**Issue by Bubbler-4** [uiua-lang/uiua#155]
* Solo: monadic function that takes an array and adds a leading axis of length 1. Exists in BQN.
* Fold-scan: a version of scan that takes an initial value.
* Repeat-collect: a version of repeat that collects the intermediate results into an array.

**Comment by teeth-eator** [comment]
By collecting into an array do you mean something like [this](https://www.uiua.org/pad?src=W-KNpSguw5cyKV0yMCAx)?

As for fold-scan I think you could just join the initial value and then drop it

**Comment by Bubbler-4** [comment]
You can't join the initial value when it has an incompatible shape. The other two are reasonable I guess.

**Comment by teeth-eator** [comment]
> You can't join the initial value when it has an incompatible shape.

You can with `fill`. although at that point it does become a bit convoluted

**Comment by teeth-eator** [comment]
Re: function suggestions, I would love to be able to decouple an array, i.e. separately push all of its rows onto the stack

[Nevermind, figured it out](https://www.uiua.org/pad?src=4oaYMVvijaUoLsOXMildMjAgMQouCjvijaUo4oqDJ-KGmDHiiqIp4qe7Lg==)

**Comment by iFreilicht** [comment]
@teeth-eator I think you might be interested in [this 2-character solution](https://uiua.org/pad?src=4oaYMVvijaUoLsOXMildMjAgMQouCi_iiJg=)

**Comment by teeth-eator** [comment]
I am. Thanks

**Comment by iFreilicht** [comment]
>You can't join the initial value when it has an incompatible shape.

@Bubbler-4 You can just insert the value into an array that you can then join on with `[∘]`, which as @teeth-eator explained is the solo function you're talking about.

Since version 0.21.0, custom modifiers and ocean notation allow you to [implement fold-scan pretty easily](https://uiua.org/pad?src=Rm9sZFNjYW4hIOKGkCDiiKfii4R-KOKKgiDiioMoXjLiiqIp4oiYKSBb4oiYXQoKRm9sZFNjYW4hKyAyIOKHoTUKCkZvbGRTY2FuIcOXIDNfNCArMeKHoTU=):

```
FoldScan! ← ∧⋄~(⊂ ⊃(^2⊢)∘) [∘]
```

**Comment by kaikalii** [comment]
All of these can be implemented in 3 or fewer characters, and they aren't common enough to warrant fewer.
I'm going to close this for now.
