### ISSUE TITLE
regex not matching multiple capture groups

### ISSUE THREAD

**Issue by TeddyDD** [uiua-lang/uiua#157]
```
regex "(a)(b)c" "abc"
```
Returns 

```
[⌜abc⌟]
```

Documentations states „Returns an list of boxed strings, with *one string per matching group*” so I'd expect

```
[⌜a⌟ ⌜b⌟]
```

**Comment by kaikalii** [comment]
Fixed in 15cc944557ff3f.
Should be live in a couple days when I release the new version, but you can try it on `dev` if you like.

**Comment by goyalyashpal** [comment]
how about returning like the PCRE? where in returned answer, group 0 corresponds to the whole match, & all the rest follow the group numbering as in the regexpression.

this will fit nicely with uiua as it also is 0-indexed.

`# assert : match dip. [⌜abc⌟ ⌜a⌟ ⌜b⌟] regex "(a)(b)c" "abc"`

```uiua
⍤∶ ≅ ⊙. {"abc" "a" "b"} regex "(a)(b)c" "abc"
```

**Comment by kaikalii** [comment]
Yep, that is what is basically what is returned.
```
regex "(a)(b)c" "abc"
```
now gives
```
[⌜abc⌟ ⌜a⌟ ⌜b⌟]
```
