### ISSUE TITLE
site: Page titles should reflect the content of the page

### ISSUE THREAD

**Issue by cogwheel** [uiua-lang/uiua#159]
Every page title on the site is `Uiua`. This gets very tedious when reading through docs in tabs:

![image](https://github.com/uiua-lang/uiua/assets/2105215/2e734c9f-08de-4e6b-8023-74e4e79b4ed7)

**Comment by kaikalii** [comment]
I've tried to do this, but I actually don't know how to do it in the web framework I'm using, Leptos.
I'd appreciate any help.

**Comment by wackbyte** [comment]
You can use the [`Title`](https://docs.rs/leptos_meta/latest/leptos_meta/fn.Title.html) component from `leptos_meta`.
