### ISSUE TITLE
uiua / uiua watch unwrapped result is PathNotFound 

### ISSUE THREAD

**Issue by nskobelevs** [uiua-lang/uiua#16]
### Unexpected Behaviour:
Running `uiua` or `uiua watch` (after `uiua init`) causes a crash due to an `unwrap()`'ed Result.

```
Message:  called `Result::unwrap()` on an `Err` value: Error { kind: PathNotFound, paths: [""] }
Location: src/main.rs:182
```

**Source code:**
https://github.com/uiua-lang/uiua/blob/3603b8cc4b1247e89ba2c96773c65ba60d2b4ede/src/main.rs#L177-L183

### Likely Cause:
I don't think the empty sting `""` does not represent the current directory on MacOS.

### Fix:
Using `Path::new(".")` fixed the issue for me locally

### Details 
**Rustc Version:** rustc 1.72.1 (d5c2e9c34 2023-09-13)
**Cargo Version:** cargo 1.72.1 (103a7ff2e 2023-08-15)
**Uiua Commit:** #3603b8c
**OS:** MacOS Sonoma 14.0

**Comment by kaikalii** [comment]
Good to know, thanks.
Fixed in db78af5
