### ISSUE TITLE
Sure -j 1 doesn't work.

### ISSUE THREAD

**Issue by jackokring** [uiua-lang/uiua#160]
`cargo` consumes all memory and stalls on `cargo build` due to ass hattery.

**Comment by kaikalii** [comment]
I'm sorry you're having issues. What can I do to help you?

**Comment by jackokring** [comment]
I'm trying a `lto = false` in the `.toml` to maybe make a larger but less intensive compile (I assume it's a unused function elimination at link time bad algorithm, with no disk temp flush).

**Comment by jackokring** [comment]
This Chromebook debian has about 2GB.

**Comment by jackokring** [comment]
It looks lovely though. I'm having VSCode issues in general (hamas++ node err,er...?) but I assume it will eventually be nice. Maybe I'll grow on it. I've already made a `cult-cargo.sh` to remove the cache as I assume this repo makes a portable binary (arm64) I can place in `~/bin`. I'll let you know when I get the VSCode working, and close this issue, as I expect the lto thing to work.

**Comment by jackokring** [comment]
Ok, it fixes it for me. `uiua watch` the terminal in VSCode ... OK. Closed.
