### ISSUE TITLE
Flip arguments for power

### ISSUE THREAD

**Issue by onagano** [uiua-lang/uiua#162]
Currently the order is `power x base` but I suggest `power base x` is more coherent and provably be renamed to `exponent`.

The inverse, `logarithm`, has already this order. Power or exponent and logarithm functions are 2-args and non-commutative, just like `subtract` and `divide`, but those are rather a 1-arg function happens to manifest its base.

Note that changing base is just a multiplication of its input, just like cosine is defined as adding a constant to the input of sine: `Cosine ← ○ + η`.

```
Exp ← ⁿ∶e
Exp 1
ExpTwo ← Exp × ₙe2
ExpTwo 1
ExpTen ← Exp × ₙe10
ExpTen 1
```

**Comment by onagano** [comment]
I mean the exponent function deserves to be a builtin primitive than power function.

**Comment by goyalyashpal** [comment]
current order of power makes sense for alot things power: square `ⁿ2` square, cube `ⁿ3`,  sqrm `ⁿ0.5` sqrt, cbrt `ⁿ ÷3 1`,  polynomials, & what not for both scalars & vectors alike.

so, massive dislike for that aspect of issue description

i have no say on exp being a separate builtin

**Comment by kaikalii** [comment]
This is interesting to me.
I think that in practice, you don't actually need `power` as it is right now.
`×.` and `√` handle the most common cases.
Also, them being inverses would have some nice consequences for `invert` and `under` I think.

**Comment by kaikalii** [comment]
While this initially appealed to me, I now think that it is *useful*  to have `power` and `logarithm` not express two sides of the same relationship.
In particular, `invert` `power` gives an nth root, which is not as nice with `exponent`.
I am closing this for now.

**Comment by goyalyashpal** [comment]
> `invert` `power` gives an nth root

```uiua
⍘ⁿ 3 27
```

Error:

```
27
3

Error: No inverse found
   ╭─[:1:1]
 1 │ ⍘ⁿ 3 27
   │ ─  
───╯
```
