### ISSUE TITLE
Break is broken inside fold

### ISSUE THREAD

**Issue by iFreilicht** [uiua-lang/uiua#164]
On dev (https://github.com/uiua-lang/uiua/commit/9ac8b5773fd546b9bce217e3221c328723f7e1d4), the following code outputs 11, as expected, but also shows an error message:

```
∧⋄∸(⎋>10.+) 10 [1 2 3]
```
```
11

Error: Break amount exceeded loop depth
   ╭─[:1:5]
 1 │ ∧⋄∸(⎋>10.+) 10 [1 2 3]
   │     ─  
───╯
  in fn from 1:4 at 1:1
```

The equivalent `∧(⎋>10.+) 10 [1 2 3]` [works as expected on main](https://www.uiua.org/pad?src=4oinKOKOiz4xMC4rKSAxMCBbMSAyIDNd).

**Comment by kaikalii** [comment]
Fixed in f34fffc2e67ccf85ca46
