### ISSUE TITLE
Incorrect rank list function throws no error inside rows

### ISSUE THREAD

**Issue by iFreilicht** [uiua-lang/uiua#165]
On dev (https://github.com/uiua-lang/uiua/commit/9ac8b5773fd546b9bce217e3221c328723f7e1d4), the following code throw an error, as expected:

```
0_2_3
∧↥ []
```
```
Error: Fold's rank list function must take 0 or 1 arguments, but its signature is |2.1
   ╭─[:5:1]
 5 │ ∧↥ []
   │ ─  
───╯
```

However, the error disappears when fold is wrapped in rows, and fold just silently assumes that the rank list is a single infinity (or rock):

```
[0_2_3 1_0_4 8_2_1]
≡(∧↥ [])
```
```
╭─       
╷ 0 2 3  
  1 0 4  
  8 2 1  
        ╯
```
I would expect it to fail in this scenario as well.

**Comment by kaikalii** [comment]
Fixed in 1dfd19d1a805
