### ISSUE TITLE
suggestion: Box array sugar

### ISSUE THREAD

**Issue by cogwheel** [uiua-lang/uiua#169]
There is some asymmetry in the way box arrays are handled vs. normal arrays. [Consider this example](https://www.uiua.org/pad?src=4oqe4oqCIFtAYSBAYl0gW0BjIEBkXQriip7iioIge0BhIEBifSB7QGMgQGR9CuKKnijiioLiiKniipQpIHtAYSBAYn0ge0BjIEBkfQ==):

```uiua
⊞⊂ [@a @b] [@c @d]
⊞⊂ {@a @b} {@c @d}
⊞(□⊂∩⊔) {@a @b} {@c @d}
```

```text
╭─      
╷ "ac"  
╷ "ad"  
        
  "bc"  
  "bd"  
       ╯
╭─       
╷ □a □c  
╷ □a □d  
         
  □b □c  
  □b □d  
        ╯
╭─           
╷ ⌜ac⌟ ⌜ad⌟  
  ⌜bc⌟ ⌜bd⌟  
            ╯
```

Naively, I expected the 2nd line to create something more like the 1st. But since boxes are scalars (functions that return arrays), `join` couples them as a pair rather than creating a new box with joined contents.

Would it be possible, when it makes sense, for functions to "jump through" boxes, treat them as normal arrays and then box them back up?

Or perhaps there is/could be a more straightforward way to express `(□ SomeFn ∩⊔)` that I missed? Something like a forked version of "under"?

**Comment by cogwheel** [comment]
> Or perhaps there is/could be a more straightforward way to express `(□ SomeFn ∩⊔)` that I missed? Something like a forked version of "under"?

Oh... it looks like `pack` does this trick.

```uiua
⊐⊞⊂ {"a" "b"} {"c" "dee"}
```

```text
╭─             
╷ ⌜ac⌟ ⌜adee⌟  
  ⌜bc⌟ ⌜bdee⌟  
              ╯
```

**Comment by kaikalii** [comment]
> functions that return arrays

This has actually be changed! Boxes are their own thing now.
It is deliberate for boxes to `join`, `couple`, etc as individual elements rather then their contents.
I'm glad you found `pack`; that's exactly what it's for!
