### ISSUE TITLE
Pick doesn't allow rank 3 array when in under

### ISSUE THREAD

**Issue by iFreilicht** [uiua-lang/uiua#171]
See [this pad](https://uiua.org/pad?src=4oqhWzJfMSAzXzJdIOKGrzXiipo1CuKNnCfiiqFbMl8xIDNfMl0nKzEg4oavNeKKmjU=):

`⊡[2_1 3_2] ↯5⊚5` works fine.
`⍜'⊡[2_1 3_2]'+1 ↯5⊚5` errors out.

**Comment by kaikalii** [comment]
This is due to the fact that `under` with multidimensional `pick` simply isn't implemented.
I want to get to it eventually.
For now, I'll improve the error message to make that clear.

**Comment by kaikalii** [comment]
Fixed in 5bb1389fd0469533f333
