### ISSUE TITLE
Interpreter sees joined and modified emoji as multiple

### ISSUE THREAD

**Issue by r-tae** [uiua-lang/uiua#172]
(Found while testing #167, but I figured it wasn't specifically pad related)

All of these look like single emoji but break as if they were multiple:

[heart, VS16](https://uiua.org/pad?src=4p2k77iPIOKGkCAkIGhlYXJ0CiAgICAkIGVtb2ppIHNlbGVjdG9y) (this is the regular emoji heart and imo this should definitely work, even if the rest aren't important)
[person, ZWJ 🧑‍❤‍🧑](https://uiua.org/pad?src=8J-nkeKAjeKdpOKAjfCfp5Eg4oaQICQgcGVyc29uCiAgICAkIFpXSgogICAgJCBoZWFydAogICAgJCBaV0oKICAgICQgcGVyc29u)
[person, skin tone, ZWJ 🧑🏿‍❤‍🧑🏻](https://uiua.org/pad?src=8J-nkfCfj7_igI3inaTigI3wn6eR8J-PuyDihpAgJCBwZXJzb24KICAgICQgc2tpbiB0b25lCiAgICAkIFpXSgogICAgJCBoZWFydAogICAgJCBaV0oKICAgICQgcGVyc29uCiAgICAkIHNraW4gdG9uZQ==)
[person, skin tone 👦🏾](https://uiua.org/pad?src=8J-RpvCfj74g4oaQICQgcGVyc29uCiAgICAkIHNraW4gdG9uZQ==)

Also this works perfectly fine:

[binding to the ZWJ](https://uiua.org/pad?src=4oCNIOKGkCAkIFpXSgoK4oCN)

**Comment by kaikalii** [comment]
I've made a preliminary fix for this in 540ac08130879. 
Each grapheme will be considered a single character.
I still have some work to do making spans correct, but all your example seem to parse correctly.

**Comment by hamidb80** [comment]
the issue with using emojis is that they cannot be colored (e.g. single argument functions get green, double argument functions get blue , ... )

**Comment by kaikalii** [comment]
I believe this was actually completed a while ago, so I am closing this.
