### ISSUE TITLE
⍜ₙ (under log) is mathematically weird

### ISSUE THREAD

**Issue by Bubbler-4** [uiua-lang/uiua#173]
[Pad link](https://www.uiua.org/pad?src=ZiDihpAg4o2c4oKZ4oiYCmYgMiA4CmYgMyA5)

```
f ← ⍜ₙ∘
f 2 8 # Expected result is 8, but evaluates to 9
f 3 9 # Expected result is 9, but evaluates to 8
```

`⍜ₙ` seems to copy the first argument on the top and call `ⁿ` as the inverse of `ₙ`, but it is not the correct inverse. It should be `ⁿ:` instead IMO.

**Comment by kaikalii** [comment]
Fixed in d1a53e3db0b1c65ee477
