### ISSUE TITLE
`Chunk size must be non-zero` in `select` and `keep`

### ISSUE THREAD

**Issue by olus2000** [uiua-lang/uiua#174]
**Version 0.0.22**

When `select` and `keep` (and maybe others, I didn't do an exhaustive check) are given an array of shape `[1 0]` the application panics with message "chunk size must be non-zero".

## How to reproduce

Run code `⊏[[]]0` and `▽[1][[]]`.

## Expected outcome

The first snippet outputs an array of shape `[1 0]`, the second a array of shape `[0]`.

## Actual outcome

Running any of these snippets causes the interpreter application to panic. You can see [error log of the select snippet](https://pastebin.com/YgK078Tu) and [error log of the keep snippet](https://pastebin.com/rC0003aG) on pastebin, both with `RUST_BACKTRACE=full` enabled.

**Comment by kaikalii** [comment]
Fixed in 51b4823b4a984e9f.
I believe the second shape should also be `[1 0]`.
