### ISSUE TITLE
No crates.io crate

### ISSUE THREAD

**Issue by nskobelevs** [uiua-lang/uiua#18]
This repo has been around for a while but it seems there's no crates.io package published.

It would be beneficial to publish this on crates (ASAP in my opinion) as it'll allow easier install with `cargo install uiua` but also to allow others to use the library as a dependency easier.

At the very least it'll reserve the crate for future use before someone else does so.

**Comment by kaikalii** [comment]
I don't want to make it available as a crate until I have worked on the public API.
I am planning on working on it this weekend.

**Comment by nskobelevs** [comment]
That's very fair! Just thought I'd suggest at least reserving the crate even if it's empty as if someone else does it first, you might not be able to get it

**Comment by kaikalii** [comment]
Oh! I didn't think about that!
Published
