### ISSUE TITLE
`⊢⍖` and `⊢⇌⍖` optimizations are incorrect

### ISSUE THREAD

**Issue by Bubbler-4** [uiua-lang/uiua#187]
[Pad link](https://www.uiua.org/pad?src=4oqi4oeM4o2WIDlfMF8wXzEK4oqi4oiY4oeM4oiY4o2WIDlfMF8wXzEK4oqi4o2PIDlfMF8wXzEKCuKKouKHjOKNjyAxXzlfOV8wCuKKouKNliAxXzlfOV8wCuKKouKImOKNliAxXzlfOV8wCg==)

`⊢⇌⍖` is "*last* index of minimum", while `⊢⍏` is "*first* index of minimum". Same for `⊢⍖` and `⊢⇌⍏`: the former is "*first* index of maximum" while the latter is "*last* index of maximum". The [current code](https://github.com/uiua-lang/uiua/blob/bb0e2bdd60e4a3d586fa97351759c0baa2e1a09c/src/compile.rs#L251) seems to not distinguish between first and last versions, which is incorrect.

**Comment by kaikalii** [comment]
Good catch, thanks!
Fixed in dd8d1868505261.
