### ISSUE TITLE
Builtin function names get formatted in user-defined function names if followed by a capital letter

### ISSUE THREAD

**Issue by teeth-eator** [uiua-lang/uiua#192]
Example:

```
Orange
orange
ranger
rangeR
```
Gets formatted as:
```
Orange
orange
ranger
⇡R
```
Expected outcome:
no formatting or a warning against using lower camelCase

---
You can close this issue if this behavior is intentional

**Comment by kaikalii** [comment]
Yep, this is intentional.
It's a bit unfortunate I guess that this happens when you are trying to *declare* a binding, but primitive name resolution happens in the lexer, so it can't be avoided.

**Comment by teeth-eator** [comment]
Nevermind, you do get a warning for using camel case, just not if it gets formatted first
