### ISSUE TITLE
Suggestion: add support to fill modifier for parse

### ISSUE THREAD

**Issue by MaloJaffre** [uiua-lang/uiua#195]
It could be useful to provide a default value for parse when the argument is not parseable:

```
⬚0parse "invalid"
```
would return 0

It would be coherent with ⬚0⊏ for example
Thanks for your beautiful language!

**Comment by kaikalii** [comment]
This is what [try](https://uiua.org/docs/try) is for.

**Comment by MaloJaffre** [comment]
Thanks for the alternative!

In my opinion it's just a bit weird that fill will return a default value for select and pick but not for parse.
Of course, i let you decide if you want to add this behavior to fill to make it a bit more consistent.

**Comment by kaikalii** [comment]
In general, `fill` is meant to fix incompatibilities in the shapes of values.
The error generated by `parse` does not have to do with shapes but with the value itself.

**Comment by MaloJaffre** [comment]
Ok, it's clearer now, thanks!
