### ISSUE TITLE
Is there a reason to not have a last (⊣) symbol?

### ISSUE THREAD

**Issue by poggingfish** [uiua-lang/uiua#213]
I know you can do `⇌⊢⇌` to have the same effect. But is there a reason that ⊣ doesn't exist to do the same thing?

**Comment by kaikalii** [comment]
Last is `⊢⇌`. It is optimized in the interpreter to be O(1).
There is no last glyph because it is trivially implementable with just 2 others.
Also `⊣A` doesn't have the same visual metaphor of being a sort of bookend.

**Comment by poggingfish** [comment]
Okay! Thank you.
