### ISSUE TITLE
Placeholders broken in switch functions

### ISSUE THREAD

**Issue by TheGitHub428Guy** [uiua-lang/uiua#214]
Example code ([pad link](https://uiua.org/pad?src=RiE9KF4xfGlkKQpGIXNpbjBgZXRh))
```
F!=(^1|id)
F!sin0`eta
```
Expected result is `¯1`, but instead it errors:
```
¯η

Error: Error getting placeholder function. This is a bug in the interpreter.
  at 1:7
1 | F! ← (^1|∘)
          ──
  in fn from 1:7 at 1:6
  in `F!`        at 2:1
```
This error seems to only occur if/when trying to call the placeholder (try changing the `0` to a `1`).

**Comment by kaikalii** [comment]
Fixed in 6d3111c100a76157e72
