### ISSUE TITLE
Uiua installed from the AUR crashes on startup

### ISSUE THREAD

**Issue by dwolv** [uiua-lang/uiua#22]
I installed from the AUR using the latest stable Rust (from Rustup) and whenever I try to run Uiua it panics like so:

```
~ $ uiua init
Profiling... warmup 1/3The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: Run(3:1: "Cannot infer function signature: /'s function · has 0 args, expected 2")
Location: src/profile.rs:92

Backtrace omitted.

Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

Installing via Cargo works like normal, though.

**Comment by crmsnbleyd** [comment]
I'm not an arch user, but maybe substituting the commit in the pkgbuild for HEAD would work?

**Comment by kaikalii** [comment]
Did you install Uiua with the `--all-features` flag?
If so, you enabled the `profile` feature, which short-circuits the interpreter and runs a profiler.
The profiling code needs to be updated.

**Comment by wackbyte** [comment]
Yes, the PKGBUILD uses `--all-features`. I've posted a comment on the package to let the maintainer know that it is broken

**Comment by wackbyte** [comment]
[This has been fixed upstream :)](https://aur.archlinux.org/packages/uiua#comment-936316)
