### ISSUE TITLE
Unexpected under bits applied to 0

### ISSUE THREAD

**Issue by aeqz** [uiua-lang/uiua#225]
**Version 0.1.0**

I would expect that `⍜f∘` (identity under an invertible function `f`) behaves the same as `∘` (identity), and that is the case that I found so far, but I have noticed that `⍜⋯∘0` (identity under `bits` applied to `0`) returns `[]` instead of `0`. That's because `⋯0` returns `[]` and `⍘⋯[]` returns `[]` again (`⍘⋯[0]` returns 0 though).

Maybe `⍘⋯[]` could return `0` instead, but I guess that there is an ambiguity regarding which rank `[]` should be inferred: 1 if it meant to be the binary representation of `0`, or 2 if it meant to be an empty array of binary representations.

Should `⋯0` return `[0]` instead for avoiding this ambiguity with `⋯`'s result?

## Motivation

I wrote a function that computes the bitwise AND of two numbers as `⍘⋯⬚0×∩(⋯)`, and found an error when both arguments are `0` because it produced `[]` and the remaining program expected a number.

**Comment by kaikalii** [comment]
In f272bbef85ac, I've made `⍘⋯[]` give `0`, `⍘⋯[[]]` give `[0]`, etc

**Comment by aeqz** [comment]
Thank you for the quick response! It sounds good.

But now `⍜⋯∘[]` crashes, which returns `[]` in version 0.1.0, so I don't know if it relates to this solution. Now that I tried, there seem to be other inconsistencies with arrays that contain only 0s: `⍜⋯∘[0 0 2]` returns `[0 0 2]`, but `⍜⋯∘[0 0 0]` crashes on `main` and returns a `[0 0]` shape array on 0.1.0.

Maybe I'm wrong, but I suspect that the ambiguity of `[]` being the binary representation of 0 and, at the same time, an empty arguments array (because `bits` is pervasive) is the root cause of these inconsistencies.

**Comment by kaikalii** [comment]
Sorry about that.
This should be fixed in 0732a1d21e72ac6bf.
I've also added some tests.
