### ISSUE TITLE
execution permissions with `uiua stand`

### ISSUE THREAD

**Issue by BaerLKR** [uiua-lang/uiua#226]
When running uiua with the `stand` option the binary that is produced does not have execution permissions (`rw-r--r--`). Before executing I manually had to make it executable with `chmod`. This could be fixed by setting the metadata of that file when writing it. 
One option would be to use `OpenOptions`with `std::os::unix::fs::OpenOptionsExt` to set the mode.

**Comment by kaikalii** [comment]
Should be fixed in b30f0569f41e243a
