### ISSUE TITLE
Stack direction for the condition of `do` 

### ISSUE THREAD

**Issue by shnarazk** [uiua-lang/uiua#229]
Why the stack used by the condition of `do` is reversed?

https://github.com/uiua-lang/uiua/blob/5556c7db256c2c94d2fafa9e4d89e45759ab6259/src/algorithm/loops.rs#L99

```
⍢(×2)(|2 <3;dump∘) 1 "something (un)related"

┌╴1:13
├╴"something (un)related"
├╴1
├╴1
├╴"something (un)related"
└╴╴╴╴╴
┌╴1:13
├╴"something (un)related"
├╴2
├╴2
├╴"something (un)related"
└╴╴╴╴╴
┌╴1:13
├╴"something (un)related"
├╴4
├╴4
├╴"something (un)related"
└╴╴╴╴╴
"something (un)related"
4
```

https://www.uiua.org/pad?src=4o2iKMOXMikofDIgPDM7ZHVtcOKImCkgMSAic29tZXRoaW5nIHVucmVsYXRlZCIK

**Comment by kaikalii** [comment]
It's a mistake.
Fixed in ce8361eafb6fe4
