### ISSUE TITLE
LSP not returning semantic tokens

### ISSUE THREAD

**Issue by Froloket64** [uiua-lang/uiua#230]
Hey, I'm writing a debugger for Uiua (e.g. to step through code and show stack at each point) and I'm trying to get parsed tokens for a local file using `uiua lsp` and passing requests to it. Unfortunately, I can't seem to get a proper response for `textDocument/semanticTokens/full`, it just returns `result: null`.

Here's the full reponse log (including `initialized`):
```
# --- Response to `initialize`
{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Initializing Uiua language server","type":3}}

{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Client capabilities: ClientCapabilities {\n    workspace: None,\n    text_document: None,\n    window: None,\n    general: None,\n    experimental: None,\n}","type":3}}

{"jsonrpc":"2.0","result":{"capabilities":{"documentFormattingProvider":true,"hoverProvider":true,"semanticTokensProvider":{"full":true,"legend":{"tokenModifiers":[],"tokenTypes":["string","number","comment","stack-function","noadic-function","monadic-function","dyadic-function","monadic-modifier","dyadic-modifier"]},"range":true},"textDocumentSync":1}},"id":1}

# --- Response to `textDocument/semanticTokens/ful`
{"jsonrpc":"2.0","result":null,"id":2}

{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Semantic tokens file:///path/to/file.ua","type":3}}
```

The request that I send to get semantic tokens:
```
{
  "jsonrpc": "2.0",
  "id": 2,
  "method": "textDocument/semanticTokens/full",
  "params": {
    "textDocument": {
      "uri": "file:///path/to/file.ua"
    }
  }
}
```

**NOTE**: The file **does** certainly exist (otherwise, `Path::canonicalize()` would fail, but also I checked manually)

File's contents:
```
≐+1_2 ↯3_3 ↘1 ⇡10
```

I'm using latest version - 0.1.0 (crates.io)

**Comment by kaikalii** [comment]
I'm not sure why this might be the case.
You might inspect the [semantic tokens code](https://github.com/uiua-lang/uiua/blob/main/src/lsp.rs#L494).

**Comment by Froloket64** [comment]
Could you explain the purpose of this code and what is `doc` for specifically:
https://github.com/uiua-lang/uiua/blob/3ea1f9b0457de659be626e0d50206874d1ee898a/src/lsp.rs#L504-L508

**Comment by kaikalii** [comment]
`LspDoc` keeps track of the contents of each Uiua file that the language server is tracking, as well as some analyzed data for each one.
In this case, we are getting the `LspDoc` corresponding to the file the language client is requesting semantic tokens for.
We then iterate through the document's semantic spans and convert them to semantic token types.

**Comment by Froloket64** [comment]
Yeah, thanks, I think I've already figured out the problem. Haven't implemented the solution yet, so can't confirm, but I'm pretty sure one has to first tell a server that a file "exists" by sending `textDocument/didOpen` and only then asking for actions on the given file.

Will close the issue once I've confirmed the solution.

**Comment by Froloket64** [comment]
Yep, that was very much correct. Sending `textDocument/didOpen` before hand solved the issue. Closing
