### ISSUE TITLE
backslash is duplicated in printed string

### ISSUE THREAD

**Issue by ikepaul** [uiua-lang/uiua#236]
Maybe I'm mistaken, but when using backslash in a string, two backslashes should be used with since it needs to be escaped,
but only one should be printed. 
```
String =  ⊂ "b" ⊂ "\\"  "a"
&s String
```
Should print `"b\a"`
But instead it prints `"b\\a"`

Is this intended?

**Comment by kaikalii** [comment]
`&s` prints a debug version of the string.
&p` will print a pretty version.

**Comment by ikepaul** [comment]
Ah, makes sense.
