### ISSUE TITLE
How to put named functions on the stack without calling them?

### ISSUE THREAD

**Issue by Zollerboy1** [uiua-lang/uiua#25]
The examples for the `&i` and `use` functions both show how to import functions from another file that puts these functions onto the stack:

```
&i "example.ua"
double ← use "double" .
square ← use "square"
square double 5
```

However, the examples don't show the contents of `example.ua`, so I don't exactly know how to export these functions there. It seems that I'm supposed to put the named functions into an array onto the stack in `example.ua`, but I don't know how to put functions onto the stack without calling them. I tried it like this:

```
# example.ua
double = *2
double
```

and like this:

```
# example.ua
double = *2
[double]
```

but these both throw `Error: Stack was empty when evaluating argument 2`.

I can put the function on the stack by doing this:

```
# example.ua
double = *2
[(double)]
```

but then it's wrapped in an anonymous function and not named anymore.

How can I get this to work?

**Comment by kaikalii** [comment]
This is a bug.
For now, you can export `double_double` from your module.

**Comment by kaikalii** [comment]
Fixed in 3df5817

**Comment by Zollerboy1** [comment]
Could you still add a tutorial how to do it? Because with your fix from 3df5817 your `double_double` workaround doesn't work anymore and neither do the other methods I tried before. I suspect that all functions get de-nested so much that their name is not available anymore.

**Comment by kaikalii** [comment]
It is working correctly for me.
Can you show the code that's not working?

**Comment by Zollerboy1** [comment]
This is the simplest example I could come up with:

For this code it works:

```
echo ← ⍥(&p &sc)∞

(echo)
```

But this doesn't work:

```
echo ← (⍥(&p &sc)∞)

(echo)
```

This shows `(⍥(&p&sc)∞)` in watch mode.

However, I wrapped the function I want to export in parens, because the older version of uiua would throw an `Stack was empty when evaluating array argument 1` error otherwise, but the version compiled from the newest commit doesn't throw that error anymore, so I can get it to work.

Still, it would be nice if exporting also worked for functions wrapped in parens.

**Comment by Zollerboy1** [comment]
Also, if I'm not mistaken, there is another problem with exporting functions right now: You can only export functions with the same signature (or is there a way around that?). Maybe `use` could be reworked to just look at all bindings in the imported files instead of only the named functions on the stack?

**Comment by kaikalii** [comment]
Okay, I think I've fixed it.
I've removed the restriction about functions put into arrays having to have compatible signatures in 7e9c66ac87bc. I believe that restriction is from when the signature checker was less sophisticated.
I've made it so that binding a function value overwrites the function's name in 24c4496abfcb.
This should now work with `use` properly.
```
echo ← (⍥(&p &sc)∞)
(echo)
```

It should be noted that the example you gave:
```
echo ← ⍥(&p &sc)∞
(echo)
```
never actually terminates or binds anything, since you have an infinite loop.

**Comment by Zollerboy1** [comment]
> Okay, I think I've fixed it.
> I've removed the restriction about functions put into arrays having to have compatible signatures in 7e9c66a. I believe that restriction is from when the signature checker was less sophisticated.

Yes, that seems to work now.

However, now it seems to be impossible to call imported functions with more than 1 output. Let's say, I have the following file:

```
# foobar.ua
foo ← (|0.2 1 2)
bar ← (|0.3 3 4 5)
foo_bar
```

I've tried the following ways to call `foo`:

```
# main.ua
&i "../uiua/foo.ua"
foo ← use "foo"
foo
# prints '(foo)'
```

```
# main.ua
&i "../uiua/foo.ua"
foo ← use "foo"
!foo
# Only functions with 1 output may be explicitly called, but the function foo has 2 outputs
```

**Comment by kaikalii** [comment]
You can no longer put things on the stack on a line before a binding where you want them to be used.
You must either bind the imported module to a name to use later, or import on the same line as the binding.

So you can do
```
m ← &i "../uiua/foo.ua"
foo ← use "foo" m
foo
```
or
```
foo ← use "foo" &i "../uiua/foo.ua"
foo
```
