### ISSUE TITLE
uiua run as default subcommand

### ISSUE THREAD

**Issue by TeddyDD** [uiua-lang/uiua#252]
Most interpreters run scripts passed to them as arguments. Uiua cold behave in exact same way. `uiua run` should be a default subcommand so instead of writing `uiua run foo.ua` you could just write `uiua foo.ua`.

**Comment by kaikalii** [comment]
I'll think about this.
Currently I like being able to type `uiua` and just make it run watch mode.
But I see the value in this.

**Comment by TeddyDD** [comment]
It could still run in watch mode when executed without arguments, not sure if that's too much magic 🤔

**Comment by kaikalii** [comment]
> It could still run in watch mode when executed without arguments, not sure if that's too much magic 🤔

Nope, I think that's fine.
