### ISSUE TITLE
Invert bits done in little endian

### ISSUE THREAD

**Issue by AMayoraz** [uiua-lang/uiua#254]
Hello,
I noticed that when doing an "invert bits" (⍘⋯) The thing seems to compute values in little endian format.
For instance, If I do:
```
⍘⋯ [0 1 0 1 1 0 0 1 0 1]
```
This will give me `666` instead of `357`. To have the correct result, I have to reverse the array first:
```
⍘⋯⇌ [0 1 0 1 1 0 0 1 0 1]
```

Is this behavior intentional? If so, perhaps adding some clarification in the documentation could help prevent confusion.

Thank you for all the effort put into developing uiua. Your work is greatly appreciated!

**Comment by kaikalii** [comment]
It's totally possible I don't know the difference between little and big.
The intended implementation is for the *least* significant bit to be the first element of the array, so the behavior shown seems correct.
My understanding is that this is big endian because the *big* bit is at the *end*.

**Comment by AMayoraz** [comment]
Maybe I have this confusion because the way I read binary. For instance `13` is `1101` and `22` is `10110`. So basically The MSB is at the left of the number when I read it.

So having to reverse the array to decode binary feels a bit counterintuitive.

But I can understand it was done this way because, for instance if I do a `⇡10` it outputs `[0 1 2 3 4 5 6 7 8 9]` with the smallest number on the left. So treating binary array that way may be most likely for consistency.

**Comment by gifti258** [comment]
The behavior of `bits` is little-endian (lower indices have the lesser significant bits). So this should be changed in the documentation (maybe add what little bit-endianness means).

I think we should keep the current bit-endianness. This way you can extend the array (`fill 0 (take 32)` for example) without changing the number.

**Comment by kaikalii** [comment]
I've changed the docs to say "little-endian".
