### ISSUE TITLE
Transposing some empty arrays leads to a crash

### ISSUE THREAD

**Issue by Bubbler-4** [uiua-lang/uiua#258]
Pad link: https://www.uiua.org/pad?src=0_3_1__4o2J4oavIDJfMCAxCg==

```
⍉ ↯ 2_0 1
```

```
panicked at src\algorithm\monadic.rs:373:32:
chunk size must be non-zero
```

Experiments suggest that it crashes if and only if the input array's shape contains one or more 0s but not on the leading axis (e.g. transposing an array of shape `0_2_0` works fine, but `2_0_2` panics).

**Comment by kaikalii** [comment]
Thanks for the report!
