### ISSUE TITLE
[Suggestion] Program solver

### ISSUE THREAD

**Issue by walseb** [uiua-lang/uiua#26]
Hello!

Thanks so much for making this amazing language!

I'm learning it, but as with most languages and array languages especially, there are so many better ways of solving a problem that I don't know of.

Some languages (elisp, haskell, etc) have program solvers that can write simple programs for you using the least amount of functions possible by either iterating through all possible combinations of inputs until the correct output is reached, or by doing something smarter.

Emacs lisp has the package [suggest.el](https://github.com/Wilfred/suggest.el) that does it, and it has some awesome documentation that outlines alternatives for different languages.

Here's an example of its output:
```lisp
;; Inputs (one per line):
"Hello. World!"

;; Desired output:
'("hello" "world")

;; Suggestions (press C-c C-c to update):

(s-split-words (downcase "Hello. World!")) ;=> ("hello" "world")
                                           
(apply #'s-split-words (list (downcase "Hello. World!"))) ;=> ("hello" "world")
                                                          
(s-split-words (car (list (downcase "Hello. World!")))) ;=> ("hello" "world")
                                                        
(s-split-words (last (list (downcase "Hello. World!")))) ;=> ("hello" "world")
```

It would be amazing if someone made a program like this for Uiua, especially now that so many are learning it.

Maybe this is the wrong place to put an issue like this, please tell me if there's a better place to put it.

Thank you!

**Comment by kaikalii** [comment]
This is probably a good thing to discuss on the [Discord](https://discord.gg/3r9nrfYhCc), as I'm not really sure how I would even begin to implement something like this.
One thing you might like if you haven't found it already is the [Uiuisms](https://www.uiua.org/isms).

**Comment by walseb** [comment]
Thank you for the very useful links!

Should I close this issue? 

Otherwise it will remain until someone makes it, which might inspire someone to do it, but will probably take some time.

**Comment by goyalyashpal** [comment]
close as not planned?
