### ISSUE TITLE
∵(;,) is not equal ∵(.) I think it should equal.

### ISSUE THREAD

**Issue by nziq53** [uiua-lang/uiua#262]
I run this code:
```uiua
□4_5_6
∵(;,) ⇡4
```
I think this stdout
```uiua
⟦4 5 6⟧
[0 1 2 3]
```
but real stdout:
```uiua
[0 1 2 3]
[⟦4 5 6⟧ ⟦4 5 6⟧ ⟦4 5 6⟧ ⟦4 5 6⟧]
```

if this code:
```uiua
□4_5_6
∵(.) ⇡4
```
```uiua
⟦4 5 6⟧
[0 1 2 3]
```

is this specification?

version is 962e64c90a8a568397f1a78c32acbaf04f551d5f and 0.3.1 prerelease

**Comment by kaikalii** [comment]
The signature of `.` is `|1.2`.
The signature of `;,` is `|2.2`.
This makes `∵ each` behave differently.
This behavior is intended.

**Comment by nziq53** [comment]
> The signature of `.` is `|1.2`.
> The signature of `;,` is `|2.2`.
> This makes `∵ each` behave differently.
> This behavior is intended.

I understood design. Thank you.
