### ISSUE TITLE
Reshape behavior and its docs.

### ISSUE THREAD

**Issue by Mewp** [uiua-lang/uiua#268]
The documentation for reshape says:

> At most one of the dimensions of the new shape may be negative. This indicates that this is a derived dimension, and it will be calculated to make the total number of elements in the new shape be [≤](https://www.uiua.org/docs/less%20or%20equal) the total number of elements in the original shape.

However, calling reshape with a negative dimension and an empty array adds items to it. This seems wrong.

I'd expect that `⬚0↯¯1_2 []` would return an 0x2 array (and ideally, not require fill).

The result of `↯¯1_2 [1]` is also inconsistent with the statement from the docs, returning `[[1 1]]`.

The requirement to specify a fill value might be the real problem here, as the above part of the docs seems to apply only to reshapes without a fill. However, the docs are also wrong about the behavior with fill:
> If [⬚ fill](https://www.uiua.org/docs/fill) is used, the total number of elements in the new shape will always be equal to the total number of elements in the original shape.
Unless i'm reading this wrong, it would imply that `=1⧻♭⬚0↯¯1_2 [1]`, which also isn't true.

To reiterate, there are four related issues here:
  1. Reshape behaves in an unintuitive way—maybe it's correct, but as of now, I don't get why would it be.
  2. Assuming it's incorrect, reshape shouldn't require fill for empty arrays, when one of the dimensions is negative.
  3. Docs are wrong about reshape's behavior without fill.
  4. Docs are wrong about reshape's behavior with fill.

**Comment by kaikalii** [comment]
Deployed to the site as well.
Let me know if there are any problems.
