### ISSUE TITLE
Windows 10 prompts me with a dialog on how to run .ua files

### ISSUE THREAD

**Issue by tankorsmash** [uiua-lang/uiua#27]
Thanks for making uiua! The docs are very clear, and the inline 'glyph - name' everywhere is very nice.

![image](https://github.com/uiua-lang/uiua/assets/1312390/0c9c5dc6-e5ce-42ea-9ee7-939416d9b33a|width=100)

Steps:

* `cargo install uiua`
* `mkdir my_dir`
* `cd my_dir`
* `uiua init`
* on completion (and every invocation of `uiua watch`), the dialog opens up.
* `"Hello World"` prints out to the console

Closing the dialog window seems like its okay, but ideally it wouldn't have any at all.

I'd expect only the hello world to print and no prompt at all to open a text file in my editor.

**Comment by kaikalii** [comment]
Yes, you should pick your text editor.

**Comment by kaikalii** [comment]
Maybe I should add a message indicating what to do if this happens.

**Comment by tankorsmash** [comment]
Oh, it's trying to open an editor for me? That's definitely not something I expected it to do! I thought it would simply evaluate the file for me. I can manage my own text editor!

**Comment by kaikalii** [comment]
The idea was that you could quickly run `uiua` from any terminal and get an editor to pop up, but now that I think about it, it's kind of silly.
There is little reason to have a watching terminal session watching an editor in a different window, which is what would happen unless your terminal is already embedded in your editor.

**Comment by kaikalii** [comment]
Fixed in 2573656404a9a

**Comment by tankorsmash** [comment]
That convenience makes sense. To be clear the dialog opened just with `uiua init` too, along with `uiua watch`. 

The latest build no longer opens the dialog on `uiua watch`, thank you!
