### ISSUE TITLE
Under drop bug?

### ISSUE THREAD

**Issue by memark** [uiua-lang/uiua#273]
Is this expected behaviour?

```
⍜(↘2)∘ "ab" # => "ab"
⍜(↘3)∘ "ab" # => "b"
⍜(↘4)∘ "ab" # => ""
```

I think it's weird, and it forces me to always guard my `⍜↘` with a `⧻` check. I would expect any `⍜` function used (including `↘`) to be truly reversible when used with `∘`. Or, possibly, at least generate a runtime error if not.

Using uiua#f97ba702.

**Comment by kaikalii** [comment]
Yes, I would say that's a bug.
I'll take a look.
