### ISSUE TITLE
Unable to box value inside under function

### ISSUE THREAD

**Issue by Hessesian** [uiua-lang/uiua#275]
https://www.uiua.org/pad?src=0_4_1__TnVtcyDihpAgeyJvbmUiICJ0d28iICJ0aHJlZSIgImZvdXIiICJmaXZlIiAic2l4IiAic2V2ZW4iICJlaWdodCIgIm5pbmUifQpUZXh0IOKGkCDilqEib25lMTIzNG5pbmUiClJlcERhdGEg4oaQIOKKg-KKmeKKmeKImCjiipcx4oqQ4oyVKSDiiplUZXh0IDog4qe7IC4g4pahICJuaW5lIgriipDijZwo4oa74oqZ4oiYKSjiioIgK0AwIOKKlyAxIGR1bXDiiJgg4oiK4pahIGR1bXDiiJggTnVtcyDilqHiiqI64oaYOuKImCkg4oqDKOKKjzN84oqPMXziio8yKSAuIOKKguKKguKKgiBSZXBEYXRhCuKIik51bXMg4pahIm5pbmUiCg==

relevant line:
⊐⍜(↻⊙∘)(⊂ +@0 ⊗ 1 ⊐∊□ dump∘ Nums □⊢:↘:∘) ⊃(⊏3|⊏1|⊏2) . ⊂⊂⊂ RepData

the □⊢ refuses to box and thus member will not work, am I reading this wrong or is it a bug ? (solving advent of code day 1 fore referrence)

**Comment by kaikalii** [comment]
`pack` is surrounding that entire `under`.
So any `box`ing you do will be undone.

**Comment by Hessesian** [comment]
Shouldnt that unboxing be done when function result arrives as an argument to the function, and not affect what happens inside?

With latest changes this now works as intended
https://www.uiua.org/pad?src=0_4_1__TnVtcyDihpAgeyJvbmUiICJ0d28iICJ0aHJlZSIgImZvdXIiICJmaXZlIiAic2l4IiAic2V2ZW4iICJlaWdodCIgIm5pbmUifQpUZXh0IOKGkCDilqEib25lMTIzNG5pbmUiClJlcERhdGEg4oaQIOKKg-KKmeKKmeKImCjiipcx4oqQ4oyVKSDiiplUZXh0IDog4qe7IC4g4pahICJvbmUiCuKNnCjihrspKOKKgiArQDEg4oqXIDEgZHVtcOKImCDiiIpOdW1zIOKKojrihpg64oiYKSDiioMo4oqU4oqPM3ziipTiio8xfOKKlOKKjzIpIC4g4oqC4oqC4oqCIFJlcERhdGEK4oiKTnVtcyDilqEibmluZSIK

However I'm not able to use dump ID inside first under function to get stack, reports no inverse found, shouldn't it ignore dump?

**Comment by kaikalii** [comment]
It should, it's just not implemented yet.

**Comment by kaikalii** [comment]
`under` `dump` is now implemented and available in the latest version.
