### ISSUE TITLE
`&pf` does not flush stdout

### ISSUE THREAD

**Issue by dosisod** [uiua-lang/uiua#28]
I am trying to create a prompt for an input box, but it does not seem like `&pf` actually flushes stdout.

Code:

```
prompt ← (&sc &pf "> ")

&p prompt
```

Running:

```
$ uiua run main.ua
hello
> hello
```

I would expect that the `> ` be printed right away, but it does not get printed until after I hit enter.

Changing `"> "` to `"> \n"` fixes the issue, but now I have an extra newline:

```
>
hello
hello
```

Also, thank you for making Uiua! I have been enjoying using it for the little side project I'm currently working on.

**Comment by kaikalii** [comment]
Sorry about that oversight.
Fixed in a00334f7ee5fb3
