### ISSUE TITLE
Unable to row sum [n] + [x_n] shapes ?

### ISSUE THREAD

**Issue by Hessesian** [uiua-lang/uiua#287]
I can do
`+ 1_1 [2_2]`
`+ 1_1 [2_2 3_3]`

this breaks at

`+ 1_1 [2_2 3_3 4_4]`
So I would expect I can do rows next, but If I want 1_1 to arrive as function argument, like so:
`Coords =  /⊂ ⊞⊟.-1⇡3`
`AroundCoords = +Coords`
`AroundCoords 1_1`
I can't use + as it breaks on 3+ rows, and I can't use rows, as it will try to sum rows and complain:
Cannot rows arrays with different number of rows 9 and 2
and there is no documentation in which order function consumes stack, so I have no idea how to do function like
row (+) ArrayOfPairs 1_1

Edit: noticed I can do `fix` in front of 1_1, that way `row (+) ArrayOfPairs fix 1_1`  works, but it feels inconsistent

**Comment by kaikalii** [comment]
> noticed I can do `fix` in front of 1_1, that way `row (+) ArrayOfPairs fix 1_1` works, but it feels inconsistent

This is the intended way.
If `ArrayOfPairs` is already on the stack, and you need to `fix` 1_1, you can do `dip fix` `⊙¤`.

**Comment by kaikalii** [comment]
In the next version, you will be able to `fix` and `+` (or other pervasive functions) without having to use `rows`.

**Comment by kaikalii** [comment]
In version 0.6, things like `+ ¤1_1 [2_2 3_3 4_4]` now work.
