### ISSUE TITLE
[web] When reading a file, instead of erroring, ask the user to upload it

### ISSUE THREAD

**Issue by typecasto** [uiua-lang/uiua#288]
On the web interpreter, whenever I use &fras to input a file, I currently get an error. It would be nice if, instead of erroring, execution is paused and the browser asks you to manually select the file and upload it, so that it's possible to use large input files (for example, the advent of code problem inputs) without copying my code into a local file and using the desktop interpreter.

**Comment by kaikalii** [comment]
Try dragging a file with the name you are trying to open into the window.

**Comment by typecasto** [comment]
Awesome! In that case, I think that should get mentioned in the "file not found" error, I'm not sure if I would have figured this out on my own.
