### ISSUE TITLE
do modifier: Function signature match 

### ISSUE THREAD

**Issue by Defelo** [uiua-lang/uiua#293]
It is not possible to add explicit function signatures to functions using the `do` modifier. Consider the "Collatz sequence" example on the [do modifier documentation page](https://www.uiua.org/docs/do):

This works fine (no explicit signature on `F`):
```uiua
C ← (+1×3|÷2)=0◿2.
F ← ;⍢⊂(¬∊,,C⊢.)
F [7]
```

```
[1 2 4 8 16 5 10 20 40 13 26 52 17 34 11 22 7]
```

But this doesn't (adding the correct signature to `F`):
```uiua
C ← (+1×3|÷2)=0◿2.
F ← |1 ;⍢⊂(¬∊,,C⊢.)
F [7]
```

```
Error: Function signature mismatch:  declared |1.1 but inferred |1.3
  at 2:5
2 | F ← |1 ;⍢⊂(¬∊,,C⊢.)
        ───
```

And this does neither (explicitly adding the inferred, wrong signature to `F`):
```uiua
C ← (+1×3|÷2)=0◿2.
F ← |1.3 ;⍢⊂(¬∊,,C⊢.)
F [7]
```

```
[1 2 4 8 16 5 10 20 40 13 26 52 17 34 11 22 7]

Error: Function modified the stack by 0 values, but its signature of |1.3 implies a change of 2
  at 3:1
3 | F [7]
    ─
```

**Comment by kaikalii** [comment]
I've fixed in on `main` and the site.
I'll put out a versioned patch fixing this and a couple other bugs tomorrow.
For now, you can update locally using either
```
uiua update --main
```
or
```
cargo install --git https://github.com/uiua-lang/uiua uiua
```
