### ISSUE TITLE
Do you have some sort of community hub?

### ISSUE THREAD

**Issue by cezarin-gh** [uiua-lang/uiua#3]
Hi there, I was wondering if you guys needed any help with the website or graphics in general. I think it's a pretty cool project and I thought I could maybe help out. I didn't see any way of getting in contact with you, and I saw there is no community hub anywhere, no Discord server or Matrix group. Maybe we could make one?

Cheers.

**Comment by kaikalii** [comment]
I'd welcome your contribution.
I've made a [Discord server](https://discord.gg/3r9nrfYhCc) for discussions.
