### ISSUE TITLE
Formatter: Special treatment of shebangs

### ISSUE THREAD

**Issue by Braendle** [uiua-lang/uiua#30]
Would it be possible for the formatter to specially handle [shebangs](https://en.wikipedia.org/wiki/Shebang_(Unix)) at the beginning of a file? That means that no space is put between # and ! in the first line regardless of `config.comment_space_after_hash`?

This would allow to simply run a uiua file directly under Linux for example:

```uiua
#!/bin/env -S uiua run

"Hello World"
```

```console
./main.ua
"Hello World"
```

**Comment by kaikalii** [comment]
Added in f388fd5d8f

**Comment by goyalyashpal** [comment]
> This would allow to simply run a uiua file directly under Linux for example:
> `./main.ua`

ahww, that's what a shebang is for... awesome.
