### ISSUE TITLE
It would be nice if the docstrings included the glyph

### ISSUE THREAD

**Issue by tankorsmash** [uiua-lang/uiua#300]
This would help with the LSP, because I write the words out and don't get exposed to the actual glyphs unless I format the file.

Instead of the LSP returning
![image](https://github.com/uiua-lang/uiua/assets/1312390/c1f82ddb-8018-4c8c-b56c-5db14abf344e)
, it might look instead like:

```
take
↙ - Take the first n elements of an array
```

It seems like the LSP might be reading the [`primitive/defs.rs`](https://github.com/uiua-lang/uiua/blob/bdddd25ecd22eab3f5c5eee3cc87d2f84cfd41a4/src/primitive/defs.rs#L854) file, since I can't find the string from the screenshot anywhere else.

**Comment by kaikalii** [comment]
Do you maybe need to update?
I recently updated the LSP to include the whole docs.
![image](https://github.com/uiua-lang/uiua/assets/13109248/bb30b739-684d-441f-95f1-08aa6afe0f4c)

**Comment by tankorsmash** [comment]
Thanks so much, just updated to 0.6.1 from 0.5.1 and I've got it now!

![image](https://github.com/uiua-lang/uiua/assets/1312390/2f221011-e6e6-4ed8-bb3e-b76ed3c4896e)
