### ISSUE TITLE
Unclear error message when calling `rows`

### ISSUE THREAD

**Issue by tankorsmash** [uiua-lang/uiua#301]
Hey there,

Running the following line ([pad](https://www.uiua.org/pad?src=0_6_1__4omhKOKJjSA_IOKKmeKKmeKImCkgLiDil6sg4qe7ICwgInR3b3RociIgInR3byIK)) says:

> Error: Cannot 4 arrays with different number of rows 3 and ≡ rows

```ua
≡(≍ ? ⊙⊙∘) . ◫ ⧻ , "twothr" "two"
```

I'm not exactly sure what it's trying to say, but maybe that it's unable to join the arrays of sizes 3 and 4? Maybe `4` has a meaning but it's not clear to me as a newbie!

 The [source](https://github.com/uiua-lang/uiua/blob/bdddd25ecd22eab3f5c5eee3cc87d2f84cfd41a4/src/algorithm/zip.rs#L515) error looks like its trying to print the array out (?), but I'm not sure. The format string is different than the other one a [few lines down](https://github.com/uiua-lang/uiua/blob/bdddd25ecd22eab3f5c5eee3cc87d2f84cfd41a4/src/algorithm/zip.rs#L527).

**Comment by kaikalii** [comment]
This is a bug in the error message.
`4` and `≡ rows` are meant to be swapped.

**Comment by tankorsmash** [comment]
Thanks, I appreciate this!
