### ISSUE TITLE
euler's constant? 

### ISSUE THREAD

**Issue by longemen3000** [uiua-lang/uiua#308]
Hello, 

From reading the docs, logarithm seems to be a pervasive diadic function,but I didn't see any implementation of the natural logarithm.

Following the steps of cosine (sine + η), the natural logarithm is just the logarithm with base `e`,so implementing that constant could be useful.

**Comment by kaikalii** [comment]
https://uiua.org/docs/constants

**Comment by longemen3000** [comment]
Weird, did not saw that in the mobile docs.
![Screenshot_20231212-032608](https://github.com/uiua-lang/uiua/assets/38795484/e495f68e-1843-44b5-bc37-ce7ed3a01f2f)
