### ISSUE TITLE
Strange function arguments

### ISSUE THREAD

**Issue by Froloket64** [uiua-lang/uiua#315]
Hey, I've been migrating from `0.6.1` to `0.7.0` and I've noticed that you had changed the signature of `CodeSpan::as_str()` to contain an `FnOnce` instance. But the implementation seems to simply call that function on the result of all other operations, so why not just let the caller decide if they want a non-identity function called on the result? Currently, the caller is forced to pass a `std::convert::identity` to it (which, btw, doesn't seem to work either, because it's allegedly not `for<'a> FnOnce(&'a str)`). So, for example, this code doesn't work:
```rust
let spans: Vec<CodeSpan>; // NOTE: Initialization left out
let spans_str: Vec<String> = spans
    .clone()
    .into_iter()
    .map(|s| s.as_str(&inputs, std::convert::identity).to_owned()) // Error
    .collect();
```
Error message:
```
error[E0308]: mismatched types
   --> src/main.rs:172:18
    |
172 |         .map(|s| s.as_str(&inputs, std::convert::identity).to_owned())
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ one type is more general than the other
    |
    = note: expected trait `for<'a> FnOnce<(&'a str,)>`
               found trait `FnOnce<(&str,)>`
note: the lifetime requirement is introduced here
   --> /home/froloket/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiua-0.7.0/src/lex.rs:289:54
    |
289 |     pub fn as_str<T>(&self, inputs: &Inputs, f: impl FnOnce(&str) -> T) -> T {
    |                                                      ^^^^^^^^^^^^^^^^^

error: implementation of `FnOnce` is not general enough
   --> src/main.rs:172:18
    |
172 |         .map(|s| s.as_str(&inputs, std::convert::identity).to_owned())
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ implementation of `FnOnce` is not general enough
    |
    = note: `fn(&'2 str) -> &'2 str {identity::<&'2 str>}` must implement `FnOnce<(&'1 str,)>`, for any lifetime `'1`...
    = note: ...but it actually implements `FnOnce<(&'2 str,)>`, for some specific lifetime `'2`
```

**Comment by kaikalii** [comment]
> `s.as_str(&inputs, std::convert::identity).to_owned()`

This will not work because the `&str` passed to `Span::as_str`'s closure cannot escape the closure.

You must to `.to_owned()` inside the closure.

**Comment by Froloket64** [comment]
Ok, I understand. But still, why is that function/closure required in the first place?

**Comment by kaikalii** [comment]
Because the input strings are stored in a concurrent hashmap with guards that I wanted to abstract.

**Comment by Froloket64** [comment]
Is there a way to get rid of this required argument (or maybe make an additional method that doesn't require it (wrapper method?)), like just return the damn `&str`? Or am I not getting something?

**Comment by kaikalii** [comment]
It is not possible with the way the data is stored, for lifetime reasons.
Just do
```rust
let spans: Vec<CodeSpan>;
let spans_str: Vec<String> = spans
    .clone()
    .into_iter()
    .map(|s| s.as_str(&inputs, |s| s.into()))
    .collect();
```
or if you like
```rust
let spans: Vec<CodeSpan>;
let spans_str: Vec<String> = spans
    .clone()
    .into_iter()
    .map(|s| s.as_str(&inputs, Into::into))
    .collect();
```

**Comment by Froloket64** [comment]
Alright, thanks.
