### ISSUE TITLE
Binding inside functions would be very useful

### ISSUE THREAD

**Issue by dexterdy** [uiua-lang/uiua#34]
Hi there,

Currently when you try to bind inside a function, you get a syntax error, but it would be very useful to be able to do this. It could work as a sort of optional function arguments, while keeping all the benefits of a tacit programming language.

Example code:
```
MyAdd ← (
	Var ← 
	AnotherVar ← 
	+ Var AnotherVar
)
MyAdd 5 5
```
expected output:
```
10
```
current output:
```
Error: Expected term or `)`, found ` `
   ╭─[:2:5]
 2 │     Var ←
   │        ─  
───╯
```

P.S.
Even if you don't end up implementing this, it would be nice if the documentation and the error were clearer about this

**Comment by kaikalii** [comment]
It is a deliberate design decision to not allow this.
You are right about the documentation, so I have added a note about it right after inline functions are first introduced in the tutorial in 622194b825f38912.
