### ISSUE TITLE
requests for Android app for uiua

### ISSUE THREAD

**Issue by ayoubelmhamdi** [uiua-lang/uiua#341]
We have beautiful Android apps from [dzaima](https://github.com/dzaima) such as [Android APL](https://github.com/dzaima/APL) and [Android BQN](https://github.com/dzaima/BQN). Is there an Android app for `UIUA`, or a plan to create one? This would make writing glyphs much easier, similar to the previous apps.

**Comment by kaikalii** [comment]
I do not have the knowledge or desire to make an Android app.
It would be fine with me if anyone wanted to make on.
