### ISSUE TITLE
Pi is imprecise

### ISSUE THREAD

**Issue by JoaoFelipe3** [uiua-lang/uiua#344]
I found out that `pi` (or `sin`) is imprecise. When I went and typed `sin pi` it gave me a value very close to 0 but not 0. Same with `tau`. But when I did `sin+eta pi` it gave me -1. I think this is caused by `pi` being imprecise enough to not give 0, or `sin` is flawed.

**Comment by kaikalii** [comment]
Unfortunately, this is problem with floating-point in general.
Here's the equivalent [Rust code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=14546e2195245f5b922595e14e9e1029).

**Comment by JoaoFelipe3** [comment]
Yes, floating-point numbers are imprecise and as a programmer I know this.

**Comment by kaikalii** [comment]
Do you know of a way to make it more precise without degrading performance?
