### ISSUE TITLE
Compiler crash when importing from repl

### ISSUE THREAD

**Issue by Omnikar** [uiua-lang/uiua#350]
It appears that the compiler crashes when attempting to use an imported function from `uiua repl`. For example:
```
# add.ua
Add ← +
```
The following then crashes the compiler when used in `uiua repl`:
```
Add ← &i "add.ua" "Add"
Add 2 2
```

**Comment by kaikalii** [comment]
It's possible this was already fixed.
When I try, it looks like this:
![Screenshot 2024-01-12 144035](https://github.com/uiua-lang/uiua/assets/13109248/11f89321-6328-4d86-a562-33014cc1c5bf)

**Comment by Omnikar** [comment]
Yeah, it's been fixed on my end too.
