### ISSUE TITLE
Suggestions for alternative glyphs for six functions.

### ISSUE THREAD

**Issue by jmcwilliams403** [uiua-lang/uiua#354]
The latter two of the following are characters present in the vast majority of APL character sets and are well-supported by fonts. The first is in the same Unicode block as them.
[`◿`](https://www.uiua.org/docs/modulus) ⇒ `⊿` (`U+22BF`).
[`△`](https://www.uiua.org/docs/shape) ⇒ `∆` (`U+2206`).
[`▽`](https://www.uiua.org/docs/keep) ⇒ `∇` (`U+2207`).

The former two of the following are the strictly-APL variants of general mathematical symbols. The last is frequently found in existing APL dialects' character sets.
[`⊚`](https://www.uiua.org/docs/where) ⇒ `⌾` (`U+233E`).
[`⊛`](https://www.uiua.org/docs/classify) ⇒ `⍟` (`U+235F`).
[`⊝`](https://www.uiua.org/docs/deduplicate) ⇒ `⊖` (`U+2296`).

**Comment by kaikalii** [comment]
I'll look at what the two main supported fonts currently have for these.

**Comment by kaikalii** [comment]
Are  `⊿` (`U+22BF`) and `⌾` (`U+233E`) more widely supported in fonts? If so, they could be switched.

I think the two delta glyphs would be incorrect for `shape` and `keep`. They are meant to be equilateral triangles, and most fonts render delta as isosceles.

`deduplicate`'s glyph has recently been changed to something different.

`classify` is meant to be a circled asterisk, and most fonts render `⍟` as a circled 5-pointed star, so I don't think that one is appropriate.

**Comment by jmcwilliams403** [comment]
Of the two in question, all my fonts installed either support both options or neither. As for the rest, since you have compelling reasons for using the existing glyphs, I'll just close this issue as not important.

For what it's worth, I was trying to articulate that it would be nice if these characters (or a subset of them) were treated as interchangeable with the standard glyphs (i.e. not a complete replacement), but again, it's not super important.
