### ISSUE TITLE
Add style warning for `[id]`

### ISSUE THREAD

**Issue by JoaoFelipe3** [uiua-lang/uiua#366]
This is a minor enhancement, but please add a style warning for `[id]`, telling the user to replace it with `fix`. You could also add a warning for `{id}` and `[box]`, telling the user to replace those with `fixbox`, or for the matter, any function with a single output (multiple functions too) wrapped in braces, replacing the braces with `fix`.

**Comment by kaikalii** [comment]
I'll have to think about this.
I think there may be some cases where `[∘]` is valuable for clarity or intent.
`fix ¤` is mostly about "fixing" an array for use in a loop, while `[∘]` conveys the creation of a singleton list.

**Comment by JoaoFelipe3** [comment]
It might only be me, but I like `fix` more, because it's a single glyph, and for me, any kind of parenthesis or bracket is a little off-putting. 🫤
