### ISSUE TITLE
Cargo fails to update Uiua with `Access denied`

### ISSUE THREAD

**Issue by JoaoFelipe3** [uiua-lang/uiua#375]
Hello. I wanted to update Uiua, so I ran `uiua update --main` to update from GitHub. Then Cargo was doing great, until it was on the last step of moving the executable into place. Then it errored (username censored):

```
error: failed to move `C:\Users\******\.cargo\bin\cargo-installpuvWCb\uiua.exe` to `C:\Users\******\.cargo\bin\uiua.exe`       

Caused by:
  Acesso negado. (os error 5)
```

Just in case, "Acesso negado" in Portuguese means "access denied". I pressed Ctrl-C, went to see if I could move manually, and what would you know; Cargo deleted the install folder. I'm on Windows, as you can see by the paths. Can anyone help?

**Comment by kaikalii** [comment]
This is likely because you have the Uiua process running somewhere.
The updater cannot replace the executable while it is running.

**Comment by JoaoFelipe3** [comment]
Ah, that's because I was in VSCode.😅
I did it in vanilla PowerShell and it worked.
