### ISSUE TITLE
Site only displays Loading... message

### ISSUE THREAD

**Issue by axelbdt** [uiua-lang/uiua#376]
Hello,
Just wanted to let you know that when I attempted to browse the website, every page displays the same introductory text and a Loading message that stays at least one minute (didn't want to wait more).
Not sure if the site was tying to launch an interpreter or interactive code snippets, but I couldn't read any code sample or any documentation.

Thanks, all the best to you and your project from a random passerby. 

(Fairphone 3, eelo android, mull browser)

**Comment by kaikalii** [comment]
This can happen if you either have a poor internet connection or have Javascript disabled.
