### ISSUE TITLE
Add style warning, or interpreter optimization, for `first select`

### ISSUE THREAD

**Issue by bkDJ** [uiua-lang/uiua#377]
I've seen some uiua videos on YouTube where people do the sort idiom `select rise dup`, but they only want the first item so they follow up with `first`. What do you think about prodding them in the right direction with a style guideline, or having the interpreter perform the fastest possible calculation for a given end result.

```uiua
Values ← ⌊×1e9 [⍥⚂1e6]

⍜now(⊢⊏⍖.) Values
⍜now(⊡⊢⍖.) Values
⍜now(/↥) Values
```

The time difference is 2 orders of magnitude apart.

**Comment by kaikalii** [comment]
This has been added in 563d98bb94b86b0cd9f3.
