### ISSUE TITLE
Sixel encoding for images and output for terminals

### ISSUE THREAD

**Issue by TeddyDD** [uiua-lang/uiua#38]
Just an idea, sixel format could be used to display images in terminal.

**Comment by kaikalii** [comment]
I support this.
I have other things higher in my todo, but if anyone wants to implement this, know that you cannot use any of the existing Rust crates that depend on libsixel, as they require it as a local dependency - something I do not want to requre.
I suggest looking at [icy_sixel](https://crates.io/crates/icy_sixel)

**Comment by exxjob** [comment]
Just to note: terminal emulators have different ideas of what's worth supporting, so compatibility can be a pain. There's ReGIS, Sixel, Kitty, iTerm2, and finally mosaics and ueberzug which are entirely different things. You might find Chafa and NotCurses most flexible, both seem to have Rust wrappers, but I can't vouch for those. https://www.arewesixelyet.com

**Comment by kaikalii** [comment]
It would be part of &ims.

**Comment by JoaoFelipe3** [comment]
This should get closed, since #557 just got merged.

**Comment by TeddyDD** [comment]
Can we get other method of enabling it? I'd rather not mess with TERM variable. Perhaps env like `UIUA_ENABLE_SIXEL` or something?

**Comment by BaerLKR** [comment]
> Can we get other method of enabling it? I'd rather not mess with TERM variable. Perhaps env like `UIUA_ENABLE_SIXEL` or something?

that would easily be possible

**Comment by TeddyDD** [comment]
Since Uiua supports Sixel images now, I think this can be closed. Thanks @BaerLKR!
