### ISSUE TITLE
Optimization idea: avoid copy-on-write if all other refs are never read

### ISSUE THREAD

**Issue by bkDJ** [uiua-lang/uiua#389]
Not sure how to phrase the issue title, but the core of the issue is that performance in some cases could be greatly improved if large data are not copied if they will never be read from. I suppose usually that situation would be a developer mistake, but bear with me 🙂

For example, `insert` is practically instantaneous on a large `map`. But if there is another reference laying around, then it makes a copy of it (slow) before `insert`ing (so that the old references do not get modified). If the old ref is _never_ looked at (which static analysis should be able to determine) then the copy operation was wasteful.

## Example

```uiua
# Experimental!

map ⊃⇡⊚ 1e7
&p ⍜now insert 0 ⚂    # modify in place
&p ⍜now insert 0 ⚂ .  # make modified copy
&p ⍜now insert 0 ⚂ ⊙◌ # modify in place
&p ⍜now insert 0 ⚂ .  # make modified copy
◌◌
```

Output running `main` branch commit 2b43c8b1 on a 2023 MacBook M3:

```
0.00000286102294921875
0.021420955657958984
0.0000021457672119140625
0.020699024200439453
```

**Comment by kaikalii** [comment]
> Here's a simple demo, but I can provide a recursive example too where it would be impossible to eliminate "extra" references without changing the algorithm to be iterative.

Can you provide this?

**Comment by bkDJ** [comment]
I updated the main post with a recursive example.

**Comment by kaikalii** [comment]
Sorry, do you have a minimal example?
Also, in case you are not aware, there is a `memo` function.

**Comment by bkDJ** [comment]
Well, 2 things.

1. When trying to create a minimal recursive example, it seems it... works fine 🎉. I probably should have profiled before filing the issue (are there docs for profiling?); sorry for the bother about that. I've modified the main post to not mention recursion. What remains is philosophical, I guess.
2. I did _not_ know about `memo`, that's awesome, thanks!
