### ISSUE TITLE
[Feature Request] Allow passing --no-format to 'uiua watch'

### ISSUE THREAD

**Issue by tankorsmash** [uiua-lang/uiua#39]
The formatter is awesome, and it's great to have a consistent codestyle everywhere, but I prefer deciding when the formatter is ran, so my only option at the moment is `uiua run --no-format`.

I'm running `uiua watch` from a terminal outside my editor, and my editor doesn't reload files immediately after saving them, meaning I get 'are you sure you want to write the file, since its changed on disk' every time the formatter changes something immediately after I write my file.

My current workaround (with Powershell) is to 'watch' manually:

    while (1) { uiua run .\path\to\file.ua --no-format; sleep(0.25); clear; }

Additionally being able to tell `uiua watch` which file specifically I'd like it to watch would be nice.

Thank you!

**Comment by kaikalii** [comment]
`--no-format` added in 34016318320d.
`uiua watch` actually just looks for any `.ua` file changes in the current directory, so I don't think the ability to specify a path is necessary.
The about text for `watch` was incorrect though, so I changed it to reflect this.

**Comment by tankorsmash** [comment]
Oh I see! `uiua watch` runs `main.ua` when it starts, but if you change another file, that one will get evaluated too.

 But if you don't have a `main.ua`, `uiua watch` throws an error:

    No .ua file found nearby. Initialize one in the current directory with `uiua init`

**Comment by kaikalii** [comment]
True, that could be annoying.
Improved (fixed?) in 12bc0d3d9aa

**Comment by tankorsmash** [comment]
Perfect, both issues are solved. Thanks so much!

**Comment by goyalyashpal** [comment]
is running `uiua` equivalent to running `uiua watch`

```console
$ uiua
Watching for changes... (end with ctrl+C, use `uiua help` to see options)


$ uiua watch
Watching for changes... (end with ctrl+C, use `uiua help` to see options)

```
