### ISSUE TITLE
Add git tags

### ISSUE THREAD

**Issue by grawlinson** [uiua-lang/uiua#40]
Hi! Maintainer for the [AUR](https://aur.archlinux.org/packages/uiua) package here!

I (and other downstream packagers) would really appreciate it if the uiua project made use of git tags to tag releases.

At the moment, I see that `0.0.5` is released on `crates.io`, but no git tags are available.

**Comment by kaikalii** [comment]
Sorry, I'm not familiar with the Arch ecosystem.
Do you just mean tagging release commits with `git tag`?

**Comment by grawlinson** [comment]
Yup! That would be great. 👍

**Comment by kaikalii** [comment]
Most recent release is tagged.
I'll try to keep it so.

**Comment by Sesay081** [comment]
Sure try to keep it so

**Comment by grawlinson** [comment]
There are no git tags though? https://github.com/uiua-lang/uiua/tags

**Comment by kaikalii** [comment]
Oh I thought I just had to use `git tag` on release commits.

**Comment by kaikalii** [comment]
If someone can explain exactly what is needed, I will do it.

**Comment by shnarazk** [comment]
`git push --tags` ?

**Comment by kaikalii** [comment]
🤦‍♂️ That's it. Will do

**Comment by kaikalii** [comment]
https://github.com/uiua-lang/uiua/tags
