### ISSUE TITLE
Add Linux 64 static musl to releases

### ISSUE THREAD

**Issue by SebastianMpl** [uiua-lang/uiua#410]
Hi,
It would be great if you could add statically linked musl versions of Uiua for Linux 64 bits to the release page.

Thank you,

**Comment by kaikalii** [comment]
While this could be done, the last time I tried to use the [releases workflow](https://github.com/uiua-lang/uiua/blob/main/.github/workflows/release.yml), it did not work. I didn't make it, so I'll have to learn more about Git workflows before I can add it successfully.

**Comment by SebastianMpl** [comment]
Thank you for quick reply.
