### ISSUE TITLE
Add Advice dialog for when you try to repeat a function 1 times

### ISSUE THREAD

**Issue by ErikKoev** [uiua-lang/uiua#438]
There should be an Advice dialog for when you try to [`⍥ repeat`](https://www.uiua.org/docs/repeat) a function 1 times saying that [`⍥ repeat`](https://www.uiua.org/docs/repeat) is redundant in current context.

**Comment by bkDJ** [comment]
Just my 2 cents, I find that `⍥F Bool` can often be less noisy than`⟨∘|F⟩ Bool`.

**Comment by kaikalii** [comment]
One problem this has it the fact that switch functions can take arrays as conditions, so they are not always equivalent.
Maybe this just means that `repeat` should be able to take arrays.

**Comment by kaikalii** [comment]
This has been added in b07bc57f9b9a65c1d9eac1e321
