### ISSUE TITLE
Signature of function with infinite repetition and break is calculated incorrectly

### ISSUE THREAD

**Issue by Zollerboy1** [uiua-lang/uiua#45]
The following code compiles, even though it shouldn't

```
readLines ← (|0.1 ⍥(|1.1 ⊂∶ □ ⎋=0 ⧻ . &sc)∞ [])
readLines
```

`foo` actually returns two values here, because when the repetition breaks, the empty string is still on the stack on top of the array of strings, but the signature checker thinks that the function only returns one value.

**Comment by kaikalii** [comment]
This is a tricky one.
For now, in 1b212b6, I have made it so that if you have a repeat with a break anywhere but the end, signature checking will fail and you will have to specify the signature yourself.

**Comment by Zollerboy1** [comment]
Thank you, this is already a big help!

**Comment by kaikalii** [comment]
1b8b8184a8da09 made a signature always required for a `while` containing a `break`.
This should fix any signature problems with this.
