### ISSUE TITLE
support light terminal theme

### ISSUE THREAD

**Issue by TeddyDD** [uiua-lang/uiua#466]
Related to #224 because the core issue was not solved.

REPL and console output is unreadable on bright terminal themes, due to hardcoded pastel colors.

Let's take a look at my terminal:
![image](https://github.com/uiua-lang/uiua/assets/4397533/f3470ec1-b93a-495d-b2a9-c9813ef70465)
![image](https://github.com/uiua-lang/uiua/assets/4397533/c9c49a98-282e-4df1-bd3e-b92c254778ac)

Code printed by the REPL is not legible.

I see two solutions to this problem:
1. Use 16 standard ANSI colors according to their names and assume the user configure terminal to make colors legible in both dark and light mode.
![image](https://github.com/uiua-lang/uiua/assets/4397533/77aee20b-78bd-4438-82d8-04a919e90b56)
2. Use 24 bit color. Allow the users to configure color theme by specifying token type - color mappings (example: `Constant = #ff0000`). This can be achieved via configuration file, xresources, env variable (like LS_COLORS) etc. This method should also assume the user can change theme at any time. Perhaps `\e]11;?\a` escape code could be used to determine what theme to use?

#224 `--no-color` flag is only partial solution because I want colors while using light theme :smile: 

---

This problem does not affect the pad, code is legible in both light and dark theme.

![image](https://github.com/uiua-lang/uiua/assets/4397533/fc1288a9-993b-4d16-ad6b-e379e43b6fd7)
![image](https://github.com/uiua-lang/uiua/assets/4397533/25a5d831-605b-4de6-bf3a-de9e6759bf1b)

**Comment by kaikalii** [comment]
I have switched to ANSI colors for everything except number literals, which in my testing seem legible with the orange color in light or dark mode.

**Comment by kaikalii** [comment]
Sorry, I forgot about the colored output

**Comment by kaikalii** [comment]
Weird, the output colors look fine for me in both light and dark mode.
![image](https://github.com/uiua-lang/uiua/assets/13109248/6c94e218-7d6b-4790-8cb4-90ba3e4c23da)
![image](https://github.com/uiua-lang/uiua/assets/13109248/8ab3f722-679c-4fd4-a149-ab63eed2703a)

**Comment by kaikalii** [comment]
This may be fixed in 9796237ac13212f7b4ab.
While I see no difference in my environment, please let me know the results on yours.

**Comment by TeddyDD** [comment]
![obraz](https://github.com/uiua-lang/uiua/assets/4397533/67afad68-9bba-47df-8643-8f1050661c64)
![obraz](https://github.com/uiua-lang/uiua/assets/4397533/2532b9d5-c63b-4e6c-a61e-85c8aa13210c)

Colors are quite subtle, but it fixes the issue. Thanks!
