### ISSUE TITLE
Incorrect inverse with swapped power and log

### ISSUE THREAD

**Issue by mlochbaum** [uiua-lang/uiua#486]
[Example](https://www.uiua.org/pad?src=0_11_0-dev_1__LTo4IMKwKC06OCkgMwrDtzo4IMKwKMO3OjgpIDMK4oG_OjggwrAo4oG_OjgpIDMK4oKZOjggwrAo4oKZOjgpIDMK): expressions `-:8 °(-:8) 3` and `÷:8 °(÷:8) 3` return 3 but `ⁿ:8 °(ⁿ:8) 3` and `ₙ:8 °(ₙ:8) 3` don't. It seems `°(ⁿ:8) 3` is computed as `°(ⁿ3) 8` and similarly for log, but the inverses should be `ₙ8` for `ⁿ:8` and `ⁿ:8÷:1` for `ₙ:8`.

(Found while checking if Uiua would do better than BQN on an inverse I [had to back out](https://github.com/mlochbaum/BQNoise/commit/c9fd9bd), that is, `Tr 440` with `Tr ← ×⊙(ⁿ:2÷12)`. Not at the moment it seems.)

**Comment by kaikalii** [comment]
They should invert correctly now.
Not sure if this makes your case work though.
