### ISSUE TITLE
Code `°°°/×4` has Error: ° un was not inlined. This is a bug in the interpreter

### ISSUE THREAD

**Issue by ShawSumma** [uiua-lang/uiua#502]
The piece of code `°°°/×4` causes a bug in the interpreter.

```
Error: ° un was not inlined. This is a bug in the interpreter
  at 1:3
```

It then highlights the third `un`.

I hope this is not the same as #482

**Comment by kaikalii** [comment]
> I hope this is not the same as #482

While obviously related, the source of this error is different.

The implementation of `°°F` simply checked that `F` was invertible before returning `F` *as* the inverse.
This made `°°°F` have an uncalculated `°` in its instructions.
It was an oversight, sorry 😅
