### ISSUE TITLE
Move data between threads.

### ISSUE THREAD

**Issue by poggingfish** [uiua-lang/uiua#51]
I want to make a concurrent application in Uiua. Is there any way to move data between threads at the moment? Not sure if this is even possible without mutability

**Comment by kaikalii** [comment]
You can currently pass data to a thread when it is spawned and get data back when you `wait` on the thread handle.
There are no mutexes because there is no mutation.
Channels are something that could exist, but I'm not sure about the best API for them.

**Comment by poggingfish** [comment]
> You can currently pass data to a thread when it is spawned and get data back when you `wait` on the thread handle.
> There are no mutexes because there is no mutation.
> Channels are something that could exist, but I'm not sure about the best API for them.

I hope something like this is implemented because having to wait for a thread to finish before retreiving data kind of ruins the point of threads in the first place.

**Comment by kaikalii** [comment]
You are correct that this is necessary.
I'll see what I can do.

**Comment by kaikalii** [comment]
I have added this in `e59ebf47d3bd7d20e4`.
That commit adds the `send`, `recv`, and `tryrecv` functions.

**Comment by poggingfish** [comment]
Perfect! Im glad you have added this feature :)
