### ISSUE TITLE
Regex throws "Error: Cannot add shape [1] row to array with shape [2] rows"

### ISSUE THREAD

**Issue by tankorsmash** [uiua-lang/uiua#521]
[pad link for repro on pad's Uiua 0.12.0-dev.1](https://www.uiua.org/pad?src=0_12_0-dev_1__ImZvbyg6Py4pPyIgImZvbyIKcmVnZXgK )

```uiua
"foo(:?.)?" "foo"
regex
```
```
Error: Cannot add shape [1] row to array with shape [2] rows
  at 2:1
2 | regex
    ─────
```

Here's a [rust playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d6c0c9609759a6d0964640cf4fc41e3d) with the regex set up if it helps.

**Comment by kaikalii** [comment]
Optional captures require `fill`. Like [this](https://uiua.org/pad?src=0_12_0-dev_1__ImZvbyg6Py4pPyIgImZvbyIK4qyaW11yZWdleAo=)

**Comment by tankorsmash** [comment]
Oh, `fill` is even mentioned in [the docs](https://www.uiua.org/docs/regex), thanks!
