### ISSUE TITLE
Automatically resample decoded audio

### ISSUE THREAD

**Issue by yanqui-uxo** [uiua-lang/uiua#526]
I noticed that when I decoded and attempted to play audio from a .wav file that had a different sample rate than what was used by Uiua, it sounded sped up. I propose that Uiua automatically resample the decoded audio to match the sample rate used. I am willing to make a pull request if this is agreeable.

**Comment by kaikalii** [comment]
I could have sworn I accounted for this.
Do you have somewhere I can get the offending audio file?

**Comment by kaikalii** [comment]
Actually, the reason for this bug makes sense.
Yes, I would accept a PR.

**Comment by kaikalii** [comment]
It's also possible that `un &ae` could return the sample rate.
That way, you could resample it manually with `keep`.
It also would prevent you from mucking up the data by resampling when you don't need to.
