### ISSUE TITLE
Compiler crash in uiua v0.11

### ISSUE THREAD

**Issue by deviantdingo** [uiua-lang/uiua#527]
Reporting as per error message, full error below. 

The application panicked (crashed).
Message:  index out of bounds: the len is 0 but the index is 0
Location: /home/username/.local/share/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/uiua-0.11.1/src/array.rs:386

Backtrace omitted.

Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Error: 
The compiler has crashed!
Hooray! You found a bug!
Please report this at http://github.com/uiua-lang/uiua/issues/new or on Discord at https://discord.gg/9CU2ME4kmn.

Uiua version 0.11.1

code:
∵△ □ []

**Comment by deviantdingo** [comment]
NB: the code  (∵△ □ []) seems to behave properly in uiua pad

**Comment by deviantdingo** [comment]
Apologies for the comment spam and closing/reopening the issue: I'm bad at github ui.

**Comment by kaikalii** [comment]
This was fixed a little while ago.
You can download a dev release if you like from [here](https://github.com/uiua-lang/uiua/releases/tag/0.12.0-dev.1).
