### ISSUE TITLE
Macro does not work after join?

### ISSUE THREAD

**Issue by hamidb80** [uiua-lang/uiua#531]
Hey, I could not make a better title,

here's the code :

```ruby
Repl‼! ← ⊙◌⍜(⊏ ^!) ^! ^!

Repl‼![1 2 4] "abc" "1??0?"
## "1ab0c" 

⊃([1 2 4]|"111"|"1??0?")
?
# ├╴"1ab0c"
# ├╴"1??0?"
# ├╴"111"
# ├╴[1 2 4]
Repl‼!
## "uncertain_binary_number.ua:1:14: Index 4 is out of bounds of length 3  in Repl‼! at uncertain_binary_number.ua:12:1\n" 

```

**Comment by kaikalii** [comment]
It's important to understand that macros are not functions. They do not pull their operand arguments from the stack. Syntactically, macros behave identically to modifiers.

When you use `Repl‼!` in that way, 3 empty functions are implicitly passed as the operands.
This makes the macro evaluate to the code `⊙◌⍜(⊏|)` which is not what you are trying to do.

That said, I don't think you need a macro for this.
It seems like your function could be written as [`Repl ← ⍜⊏⋅∘ ⊙:`](https://uiua.org/pad?src=0_12_0-dev_1__UmVwbCDihpAg4o2c4oqP4ouF4oiYIOKKmToKUmVwbCBbMSAyIDRdICJhYmMiICIxPz8wPyIK)

**Comment by hamidb80** [comment]
> Repl ← ⍜⊏⋅∘ ⊙:

wow, truly amazing solution!


> When you use `Repl‼!` in that way, 3 empty functions are implicitly passed as the operands. This makes the macro evaluate to the code `⊙◌⍜(⊏|)` which is not what you are trying to do.

I was misunderstood. Thanks for your time & patience
