### ISSUE TITLE
easier way to make HTTPS requests (pretty please)

### ISSUE THREAD

**Issue by aspiringLich** [uiua-lang/uiua#57]
I'm trying to make a function that automatically grabs the input data for advent of code problems (Because why not) and unfortunately my raw HTTP requests are not going through. After a lot of eye-pressing and "400 Bad Request" errors (I'm not terribly familiar with web protocols) I figured out that the problem was that I wasn't going through HTTPS. Now, implementing RSA and dual elliptic curve encryption in uiua might be a fun way to burn a few months, but I'm lazy.

Could you provide another special function to, you know, do that?

**Comment by aspiringLich** [comment]
I could probably implement this myself, thinking about it. If this isn't done by tomorrow I'll probably use `ureq` and put the function behind an `https` feature gate.

**Comment by kaikalii** [comment]
I support having a simple built-in http get request for fun things like this.
If you do implement it, please name it `&httpget`.
It should probably take a string and return a string, although maybe something else if you want to handle headers, timeout, etc.
System functions are defined and implemented in the `src/sys.rs` file.

**Comment by aspiringLich** [comment]
#66

**Comment by aspiringLich** [comment]
oh right also this is done #66
