### ISSUE TITLE
Installation Issue with `-F full` 

### ISSUE THREAD

**Issue by seeker-3** [uiua-lang/uiua#570]
I went to the [documentation page](https://www.uiua.org/install) and followed the instructions:

> Once you have that, run one of the following commands:
> 
> `cargo install uiua -F full`
> `cargo install uiua`

and got
```
$ cargo install uiua -F full

    Updating crates.io index
  Installing uiua v0.12.3
error: failed to compile `uiua v0.12.3`, intermediate artifacts can be found at `/tmp/cargo-installozk19A`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

Caused by:
  none of the selected packages contains these features: full, did you mean: ffi, fft, tls?
  ```
 has the `full` feature flag been deprecated?

**Comment by kaikalii** [comment]
Sorry about that. The `full` flag is actually new. I've just published a `0.13.0-dev.2`, which should have the feature available.

**Comment by seeker-3** [comment]
Ah, that makes sense, so specify the version as well:

`cargo install uiua --version 0.13.0-dev.2 --features full`

Thank you, I'm looking forward to trying it out!

**Comment by kaikalii** [comment]
If you use one of the major OSs, you can download a pre-built binary of this version from the [releases page](https://github.com/uiua-lang/uiua/releases).

**Comment by seeker-3** [comment]
Ah yeah, that's much easier. I was just seeing if I could get it working in a docker container for fun, so I'm using Ubuntu. This seemed to do the trick:

```dockerfile
FROM ubuntu

ENV LANG=C.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=C.UTF-8

RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get -y install curl

RUN bash -c "$(curl -fsSL https://raw.github.com/seeker-3/what-the-dock/main/install.bash)"

RUN apt-get -y install \
    unzip \
    libasound2t64

RUN apt-get autoremove
RUN apt-get clean
RUN apt-get autoclean
RUN apt-get -f install

# Install uiua
RUN curl -fsSL -o uiua.zip https://github.com/uiua-lang/uiua/releases/download/0.13.0-dev.2/uiua-bin-x86_64-unknown-linux-gnu.zip
RUN unzip uiua.zip
RUN rm uiua.zip
RUN mkdir -p /usr/local/bin
RUN mv uiua /usr/local/bin/uiua
```

Thanks for the help!
