### ISSUE TITLE
Wouldn't left-to-right evaluation order work better for a stack language?

### ISSUE THREAD

**Issue by jackpal** [uiua-lang/uiua#572]
I've been enjoying going through the tutorial. Absolutely love the web-based IDE and the "?" operator in particular. Genius!

But one thing has been bothering me:

I have to type in all the expressions backwards. For example, the hypotenuse order of operations is  "duplicate, multiply, swap ,duplicate, multiply, add, sqrt". But the language is right associative so you have to enter the operations in the opposite order. My mind is too small to mentally reverse the algorithm, so I had to type dup, then backspace the the front and type multiply, and so on.

I assume the right hand precedence order was inherited from the array language ancestors of uiua like APL.

But it seems like it would make the language easier to write (and read) if it adopted the RPN precedence order of the stack language ancestors like FORTH.

A cheesy way of implementing this would be to have a "mirror" setting on the IDE that swapped everything before the interpreter saw it. (you'd have to do something clever about array initialization, to keep the arrays from being mirrored).

**Comment by kaikalii** [comment]
This question was asked a lot when Uiua first became public.
I outline some reasoning on [this](https://www.uiua.org/docs/rtl) page, but it really boils down to
- It's how other array languages do it
- Some glyphs make more sense when put to the left of their operands
- It's just how I like it.

I am very aware of the issue of having to constantly press left arrow when building up an expression.
You can read about the solution to this problem in [this section](https://www.uiua.org/tutorial/codetactility#line-manipulation) of the Code Tactility tutorial.

**Comment by jackpal** [comment]
Thanks! Please excuse me for filing the issue before reading all the docs. I'll look into the semicolon IDE key.
