### ISSUE TITLE
a way to convert glyphs back into name

### ISSUE THREAD

**Issue by goyalyashpal** [uiua-lang/uiua#60]
### what
a way to convert glyphs back into name

### use cases
* super helpful in migration from breaking changes in glyph designation like in #58 
* documentation or tutorial material where showing names make more sense 

e.g. for "showing names more sensible":
* recommended font [dejavu] not suitable or not to the liking - say for print media like books
* in a beginner tutorial - where you are introducing this language to newcomers & you _want_ to start with names
* in accessibility critical usage: i.e. for people with eye sight problems
* where you (content creator/book author) can't expect reader to remember specifics of any language as you are covering huge breadth of prog langs/paradigms
* better searchability of keywords

[dejavu]: https://www.uiua.org/docs/install

**Comment by kaikalii** [comment]
If someone would like to implement this, it can be added to the new formatter configuration.
This is a common request, so I'll try to get to it if I can.

**Comment by kaikalii** [comment]
My philosophy on this has changed.
Having unformatted code is not something I want to encourage.
Reasoning [here](https://github.com/uiua-lang/uiua/pull/121#issuecomment-1756502921)
