### ISSUE TITLE
crash: chunk size must be non-zero

### ISSUE THREAD

**Issue by memark** [uiua-lang/uiua#609]
Uiua 0.13.0 as well as 0.14.0-dev.2

Run the following code:
>uiua eval "⬚0+ ? =0↯⊙⊚ 1 0 [0_0 0_0]"

the interpreter crashes:
<img width="809" alt="image" src="https://github.com/user-attachments/assets/d9acafe3-365c-4613-8fe0-e6c91fd649f5">

(This is a reduced example, just in case you think that the code doesn't make much sense. 😄)

**Comment by kaikalii** [comment]
Fixed in 53466b9456c36bce.

**Comment by kaikalii** [comment]
Fixed for real in 291c99502ceb40

**Comment by memark** [comment]
Confirmed. Thanks.
