### ISSUE TITLE
open github discussions?

### ISSUE THREAD

**Issue by goyalyashpal** [uiua-lang/uiua#61]
* i don't know if it would become messy (read: duplicate/super-noob riddled) or not - given the beginner stage of the language & newcomer influx it would be getting
* but i think having a place to clear doubts is required.

^
* there is already discord (as mentioned in readme) but many ppl don't like/use that... 
* there can be others like telegram, discourse, zulipchat or what not - but previous point can apply to that too
* so, having github would be path of least resistance i guess....

**Comment by goyalyashpal** [comment]
tangential to: #3

**Comment by kaikalii** [comment]
I don't want to have too many places of discussion to monitor; keeping up with GH issues and PRs + Discord is already a lot for me.
I like Discord, so that is where I'd like to have free-form discussions.
If you have suggestions, questions, etc., it's fine to post them as GH issues.

**Comment by goyalyashpal** [comment]
> keeping up with GH issues and PRs + Discord is already a lot for me.

yp, that was also my concrn



> If you have suggestions, questions, etc., it's fine to post them as GH issues.

thanks a lot 😇
