### ISSUE TITLE
Add the ability to jump between words when pressing `Option` + `LeftArrow`/`RightArrow` in the developer pad on MacOS.

### ISSUE THREAD

**Issue by vxern** [uiua-lang/uiua#613]
Currently, pressing `Command` + `LeftArrow`/`RightArrow` jumps to the start/end of the current line, but `Option` + `LeftArrow`/`RightArrow` does nothing.

https://github.com/user-attachments/assets/35f3ae46-9c5c-45ea-879c-f33db87098bb

**Comment by kaikalii** [comment]
You do this with Ctrl

**Comment by vxern** [comment]
On Mac, the key used to jump between words is `Option`. `Control + LeftArrow/RightArrow` switches between workspaces (desktops).

**Comment by vxern** [comment]
For context, this is what happens on Discord when I use `Control`, then `Option`, then `Command` in combination with the left/right arrows.

https://github.com/user-attachments/assets/71d168c3-36af-4d86-afbf-2298c5db94cd
