### ISSUE TITLE
Add Existential / Universal Quantification Function / Uiuism

### ISSUE THREAD

**Issue by pehdfms** [uiua-lang/uiua#618]
[Existential](https://en.wikipedia.org/wiki/Existential_quantification) and [Universal](https://en.wikipedia.org/wiki/Universal_quantification) quantifications are common functions in many different modern functional languages (for example, haskell's some / all and javascript's any / every). They can be thought of as representing "there is some element such that _condition_ holds" and "for all elements, _condition_ holds".
Since it seems like this is enough of a common operation for those languages to consider adding them to their standard library, should Uiua too add quantifications to the prelude? Alternatively, we could add an Uiuism showing how to do the same.
If it seems worth adding to the prelude, I recommend using the common mathematical glyphs ∃ (there exists) and ∀ (for all).

Javascript Example:
```js 
const mixed = [1, 30, 39, 29, 10, 13];
const evens = [2, 6, 10, 20, 14];

const isEven = n => n % 2 == 0;

mixed.some(isEven);  // True
mixed.every(isEven); // False

evens.some(isEven);  // True
evens.every(isEven); // True
```

Possible Uiua Example:
```ua
Mixed ← [1, 30, 39, 29, 10, 13]
Evens ← [2, 6, 10, 20, 14]

IsEven ← =0◿

∃ IsEven Mixed # 1
∀ IsEven Mixed # 0

∃ IsEven Evens # 1
∀ IsEven Evens # 1
```

**Comment by kaikalii** [comment]
In array languages, this is done with `/ reduce`.
[Example](https://uiua.org/pad?src=0_14_0-dev_5__TWl4ZWQg4oaQIFsxIDMwIDM5IDI5IDEwIDEzXQpFdmVucyDihpAgWzIgNiAxMCAyMCAxNF0KCklzRXZlbiDihpAgwqzil78yCgov4oalIElzRXZlbiBNaXhlZAovw5cgSXNFdmVuIE1peGVkCgov4oalIElzRXZlbiBFdmVucwovw5cgSXNFdmVuIEV2ZW5zCg==)

**Comment by pehdfms** [comment]
> In array languages, this is done with `/ reduce`.
> [Example](https://uiua.org/pad?src=0_14_0-dev_5__TWl4ZWQg4oaQIFsxIDMwIDM5IDI5IDEwIDEzXQpFdmVucyDihpAgWzIgNiAxMCAyMCAxNF0KCklzRXZlbiDihpAgwqzil78yCgov4oalIElzRXZlbiBNaXhlZAovw5cgSXNFdmVuIE1peGVkCgov4oalIElzRXZlbiBFdmVucwovw5cgSXNFdmVuIEV2ZW5zCg==)

Awesome! I find using reduce maximum like that a little confusing (immediately surprising?), but that should be made irrelevant when/if "or" stabilizes.

**Comment by kaikalii** [comment]
There is an experimental function called [`∨ or`](https://www.uiua.org/docs/or), which when reduced is a better match for "any".
Not sure whether it will be stabilized though
