### ISSUE TITLE
any way to combine two lines of codes with some separator?

### ISSUE THREAD

**Issue by goyalyashpal** [uiua-lang/uiua#62]
hi! thanks for such a wonderful language & project

* i was wondering if there's any way to combine two lines of codes into one?

```uiua
# Sharing in names as the symbols may change
intd = flip dip mod floor divide over over  # intd ← ∶ →◿ ⌊÷ ,,
div = max * +1 range                        # div ← ↥ × +1 ⇡

# TESTS
intd2 +1 range6                             # intd2 +1 ⇡6   # [0 1 1 2 2 3] [1 0 1 0 1 0]
div 6                                       # div 6         # [1 1 3 2 5 3]
```

I was thinking something like any of these:
```
(div 6) (intd2 +1 ⇡6) # [1 1 3 2 5 3]
div 6; intd2 +1 ⇡6 # [1 1 3 2 5 3]
```

so, like here, 
* the `div 6` depends the output of previous command _to be_ on the stack
* being able to combine these 2 in one would make the connection clear, 
* and hence be super helpful in documenting changes while developing the function.

and: the rest others here can be commented out or even deleted as they are all same, but this outlier has to be there
* being in separate line, either of these is susceptible to deletion while doing cleaning up
* and being multi-line, these require additional line breaks before & after for distinction

a screenshot took midway during cleanup of brainstorming done on the smartphone

<img src="https://github.com/uiua-lang/uiua/assets/19423063/6766a31e-038b-4485-9223-0a3d62b7357c" width=400px/>

**Comment by goyalyashpal** [comment]
> Is the code behaving in a way that is unexpected?

y-s, cod- is working fin-; no probl-m with cod-

> Is there some way you would like to organize your code that you cannot?

yep

so, in c for example, if you hav- two lin-s of cod- and you want to mak- th-m on sam- lin-, it's no issu- as -v-ry lin- -nds with a s-micolon.

i was looking for som-thing similar so that i can m-rg- two lin-s of uiua cod- just pr-s-ntation wis- without alt-ring th-ir functionality

**Comment by kaikalii** [comment]
Can't you just put them on the same line?
```
intd ← ∶ →◿ ⌊÷ ,,
div ← ↥ × +1 ⇡

intd 2 +1 ⇡6
div 6

div 6 intd 2 +1 ⇡6
```
Output:
```
[1 1 3 2 5 3]
[1 1 3 2 5 3]
```

**Comment by goyalyashpal** [comment]
i tried - but it showed error

might be due to smth else which i conflated with merging lines 😵😵
