### ISSUE TITLE
Idiomatic Answer in string challenge doesn't pass tests

### ISSUE THREAD

**Issue by pehdfms** [uiua-lang/uiua#624]
https://www.uiua.org/tutorial/strings
Challenge 2's idiomatic answer seems to give incorrect results.

**Comment by bluebear94** [comment]
Yeah, it should be `+⊃⊢⊣ ⊜⋕ ×⊓≥≤@0,@9.` instead.

**Comment by kaikalii** [comment]
Fixed in 66fae73818364eeff4112bb
