### ISSUE TITLE
Shebang scripts parse arguments after the script path as regular args

### ISSUE THREAD

**Issue by nilium** [uiua-lang/uiua#628]
I noticed in 0.14.0-rc.1 that scripts where I'd pass a test input into a script didn't run as usual (a side effect of how I structured Advent of Code stuff). This can be pretty easily checked with a script like:

```uiua
#!/usr/bin/env uiua
# thing.ua
&p &args
```

Running it as `./thing.ua test` doesn't run the script itself and instead runs the test subcommand (this is a little easier to see with `lsp` instead, but I first noticed it with `test`).

Works under 0.13.0, so can probably narrow it down to changes around arg parsing since. I'll probably take a go at fixing it but wanted to get this written down for now since it's getting late here. I think maybe something related to 0f38f26003a56a5390181f3f8fa42b990c7839e2 since it changed arg handling after #585 / aee40c5b6c92d8c1824590406c2f18a5e31b42dd, but that's from a very, very quick scan.

**Comment by kaikalii** [comment]
I saw the PR, but I'm not sure it's the best way.
I'm not on my Linux machine right now, but I'll test solutions to this tomorrow when I am!
