### ISSUE TITLE
LFR (aka RTL) comment?

### ISSUE THREAD

**Issue by goyalyashpal** [uiua-lang/uiua#63]
hi! thanks for such a wonderful language & tooling.

as uiua's execution is LFR (#2) , so, i think having a same direction comment would help a lot in breaking down the code while reading & trying to understand.

otherwise now, at least how i do it - it becomes very very cumbersome to track down where things are going wrong.

* first break the line at left of the operation
* move line up
* move cursor down & comment the line
* move cursor back up to make edits

Attached is a screenrecord of how i do it currently (it's a bit slow, increase its playback speed to save time):

https://github.com/uiua-lang/uiua/assets/19423063/218112ee-0819-454b-9bc0-20bbc81be01a

**Comment by kaikalii** [comment]
Have you tried using [trace](https://www.uiua.org/docs/trace) or [dump](https://www.uiua.org/docs/dump)?

**Comment by goyalyashpal** [comment]
yes, i tried trace, it showed only the topmost element of stack

`dump` showed identifier unknown

and even on updating the uiua on my system, the problem with trace & dump would be that they still require cut/pasting the symbol

whereas comment can be aided with ide

**Comment by kaikalii** [comment]
`dump` is new. You have to update your interpreter installation.

**Comment by goyalyashpal** [comment]
> even on updating the uiua on my system,
> the problem with trace & dump would be that they still require cut/pasting the symbol

:)

**Comment by goyalyashpal** [comment]
one issue with `trace`, `dump`:
* is that th-r-'s no sp-cial indication for it, it just app-ars plain just lik- oth-r stacks.
* it -v-n b-hav-s th- sam- way as oth-r stacks, so, aft-r using thos- you hav- to manually r-mov- that as w-ll...
* though this last point is not too strong for `dump` as th- whol- stack is duplicat-d -ss-ntially, but for stack, it's kinda not okkay in-my-humble-opinion

-xampl-:

```uiua
[1][2]
~
+
```

output: `[1] [3]`
expeeecteed: `[3]`

**Comment by goyalyashpal** [comment]
i should sl--p now, i will contin- th- discussion som- oth-r day aft-r having mor- -xp-ri-nc-
thanks a lot for coopeeration
