### ISSUE TITLE
Pad render lock after newest optimization commit

### ISSUE THREAD

**Issue by pehdfms** [uiua-lang/uiua#632]
Copypaste the following code into the pad:
```uiua
⍜∩⋯⬚0≠ [2] [0]
```

Your pad should now stop rendering correctly, not being able to display the code you just pasted.
I haven't been able to reduce the failure case further, even altering the exact values on the arrays seems to give inconsistent results, however, I'm fairly sure that it's associated with the latest commit as I was just using the pad and only had this occur after refreshing my page.
Attempting to write the code above also leads to the same problem, so it's not entirely restricted to copypasting.

**Comment by kaikalii** [comment]
When the pad breaks, this is generally a crash in the interpreter. Unfortunately, panics cannot be caught on WASM.
I will look into this now.

**Comment by kaikalii** [comment]
I'm not sure when, but I seem to have already fixed this.
I've just deployed a new version of the pad with the fix.
