### ISSUE TITLE
Reduce on swap behaves the same as reduce on noop

### ISSUE THREAD

**Issue by downloadpizza** [uiua-lang/uiua#64]
![grafik](https://github.com/uiua-lang/uiua/assets/33293877/593f0fa1-b2ce-4881-b190-cdb722013807)
![grafik](https://github.com/uiua-lang/uiua/assets/33293877/d0a2ae38-9857-4928-906e-3cea0412a1ea)

As you can see, noop and swap behave the same in a reduce, but `,` for example does its thing

Issue is i have no idea what the actual behaviour should be. Maybe this is correct? An explanation on how unary functions are handled would be nice. My initial understanding was that
```
5_7_8
/-

is equal to

8 7 5
--
```
Obviously this doesnt make sense since then the behaviour of `/.` doesnt line up at all. It would be nice to get a good explanation on how things are applied

**Comment by kaikalii** [comment]
Reduce with a function that returns more than one value should be an error actually.
I'll fix that.

**Comment by kaikalii** [comment]
Fixed in 65293c7096a82e4
