### ISSUE TITLE
Are the permalink URLs to the uiua pad compressed in any way?

### ISSUE THREAD

**Issue by JobLeonard** [uiua-lang/uiua#77]
I just saw this in the discord:

https://uiua.org/pad?src=Z2NkIOKGkCA74o2lKOKOiz0wLuKXvyzihpLihqfihqUsLCniiJ4KYXJyR2NkIOKGkCBnY2TiiqLiiLbiiqLih4wuCmNvbXBsZXhTcXVhcmUg4oaQIFvihpIow5fDlzIpLcOXLuKItsOXLiws4oqi4oi24oqi4oeMLl0KcGFpcnMg4oaQIC_iioLiip7iioIuKzHih6EKc29ydCDihpAg4oqP4oyCLgoKdHJpcGxldHMg4oaQICgKICBwYWlycwogIOKWveKJoSg84oqi4oi24oqi4oeMLikuICMgZmlsdGVyIGZvciBvbmx5IHNvcnRlZCBwYWlycwogIOKJoShjb21wbGV4U3F1YXJlKSAjIGdldCB0cmlwbGV0cwogIOKWveKJoSg9MWFyckdjZCkuICMgZmlsdGVyIG91dCByZXBlYXRzCiAg4omhKOKKguKItuKImi8r4oG_Mi4pICMgZ2VuZXJhdGUgdGhpcmQgbnVtYmVyCiAgLiAjIHNhdmUgZm9yIGxhdGVyCiAg4omhKC8rKSAjIHN1bQogIOKGkuKItiAjIGJyaW5nIGNvbnN0YW50IGZvcndhcmQKICDiiLoow7cpICMgZmluZCByYXRpb3MKICA9MOKXvzEuICMgYnVpbGQga2VlcCBhcnJheQogIOKGkuKWvS4gIyBrZWVwIHJhdGlvCiAg4oaS4pa94oi2ICMga2VlcCB0cmlwbGV0CiAgw5cgIyBtdWx0aXBseSByYXRpbyBhbmQgdHJpcGxldAogIOKJoSgvw5cpICMgcmVkdWNlIGludG8gcHJvZHVjdAopCgp0cmlwbGV0cyAzMCAxMjA=

That's 844 characters for the base 64 portion of the URL, and it's not *that* big of a snippet. I just wanted to mention that if you throw the same source code through [lz-string](https://github.com/pieroxy/lz-string)'s url-safe compressor, it gives a string of 636 characters.

I assume that array languages generally do not compress very well in the "repeated substring" sense, but the thing is that lz-string *also* compresses by limiting itself to characters actually in the dictionary. Since there are only 68 unique characters in this linked example (and that's because of the amount of comments), this already saves about two bits per char compared to a regular UTF-8 conversion.

I'm not sure how one might add this in a backwards compatible way (also a variant algorithm more dedicated to uiua's particular "text distribution" might be more appropriate, let me know if you want me to look into that)

**Comment by kaikalii** [comment]
It's currently just base64-encoded with a URL-safe encoding.
I don't have the bandwidth to devote to this right now, but I'd welcome contribution.

**Comment by kaikalii** [comment]
I should note that a solution should probably not assume anything based on Uiua's glyphs, as the glyphset is still in flux.

**Comment by JobLeonard** [comment]
Well,  it happens that I'm into compression algorithms as a hobby and have a small personal toolkit of "compression building blocks" for JS-based experiments, so I could distill something out of that without too much mental puzzling. I just need to find the time. 

Basically, I have the mental bandwidth but not the "work hours" available for a full PR. Would writing a specialized compression/decompression function in JavaScript be a useful contribution? With comments so you can make sense of it. And then leave the part of wiring them up into the rest of the website up to you? Also even writing those functions might take a bit.

> I should note that a solution should probably not assume anything based on Uiua's glyphs, as the glyphset is still in flux.

Oh that will not be an issue. I'm thinking of a simple streaming dictionary compression that starts with an empty dictionary. It will grow as the string is processed and new glyphs are encountered, having no knowledge about which alphabet is in the string before doing so. Will spare you the details for now because bandwidth - guess you can read them as code comments later if those JS functions would be worth writing up.

**Comment by JobLeonard** [comment]
Ah, I have never written anything in Rust. Just getting over that threshold would already slow me down quite a bit :sweat_smile:. Well, I'll do the JS functions first and worry about that later.

**Comment by iFreilicht** [comment]
@JobLeonard If you ever finish that but don't have time for more, ping me!
I'd be interested in translating the JS to Rust. I use TS/JS at my day job and have only used Rust for a few projects so far, this seems like an interesting challenge and a good learning experience.

**Comment by JobLeonard** [comment]
@iFreilicht awesome! Looking forward to collaborating.

Some mental notes for myself after thinking about what would be the most cost-effective "uiua-oriented" compression approach (before I forget my conclusions again):

- given how terse the language is, the number of repeating substrings are probably negligible. Making use of the limited alphabet to reduce bits-per-glyph will likely help the most, it's not really worth the effort of doing too complicated stuff beyond that (which keeps code short and simple too)
- standard LZ77 and LZ78 are more likely to blow up final size than compress anything, . *However*, comments might include long strings of text. So perhaps a hybrid compression works? E.g. if a `#` is encountered, switch to an LZ78 variant (perhaps even separate dictionary) until a newline character is encountered, and otherwise just use a simple "encountered glyph" dictionary.
- two-glyph repetitions might be a thing? I haven't really seen anyone link code examples where I noticed that though though. If I'm wrong there are options if it is a thing (order one "prediction by partial matching", LZ78 where dictionary words don't grow beyond length two)

**Comment by iFreilicht** [comment]
A good case-study might be [this ray-tracer](https://www.uiua.org/pad?src=YXIg4oaQIMO3OSAxNgppdyDihpAgNTAKdmgg4oaQIDIKCm1kIOKGkCAxMApzbSDihpAgMjAKCmNjIOKGkCBbMCAwIDBdCgpjIOKGkCBbWzAgMCDCrzFdIFswIMKvMTAwLjUgwq8xXV0KciDihpAgWzAuNSAxMDBdCm1jIOKGkCBbWzAuNyAwLjMgMC4zXSBbMC44IDAuOCAwXV0KCmloIOKGkCDihqUx4oyKw7dhciBpdwp2dyDihpAgw5d2aCDDt2loIGl3Cgp2dSDihpAgW3Z3IDAgMF0KdnYg4oaQIFswIMKvdmggMF0KCnBkdSDihpAgw7dpdyB2dQpwZHYg4oaQIMO3aWggdnYKcGR1diDihpAgK3BkdSBwZHYKCnVsYyDihpAgLcO3MnZ1IC3DtzJ2diAtWzAgMCAxXSBjYwpweiDihpAgK8OXMC41cGR1diB1bGMKClJ2IOKGkCDihq_iiLZb4o2l4pqCXS_Dly4KCm5hbiDihpAgw7cwIDAKQmdkIOKGkCAr4o2aWzAg4oieXcOXWzEgMSAxXS3iiLYx4oi24o2aWzAg4oieXcOXWzAuNSAwLjcgMV0uw5cwLjUrMeKKoTHiiLonw7fiiLbiiLbiiJovK8OXLi4KClIg4oaQICgKICDijaUoCiAgICDijZzijZjijYkofDEKICAgICAg4oip4oip4o2JL-KImOKHjAogICAgICDiiLonLyvDlyws4oqZ4oi24oi6LWMuCiAgICAgIOKKmSjiiLrDl-KKmSguLyvDly4uKS3Dly5y4omhLyvDly4pCiAgICAgIOKImi3iiLbDly4s4oi2CiAgICAgIOKIuifDt-KItuKGp-KIqSgr4oiawq88MC4wMDEuKeKKgyst4oqZwq8KICAgICAgK8OX4qe7Y8KsPTDDlzAs4oqZL-KGp-KNmjEn4oqi4oyC4o2JLgogICAgICDiipkoLiviiLrDl-KItikKICAgICAg4oqZLeKItuKNmOKNieKNmlswIOKInl3iiqEs4oqCY1tuYW4gbmFuIG5hbl0KICAgICAg4oqZKOKIuifDt-KItuKItiniiLbijZpbMCDiiJ5d4oqhLOKKgnIgbmFuCiAgICAgIOKNmOKNieKNmlswIOKInl3iiqHiiLbiioJtY1sxIDEgMV0KICAgICAg4oqZKCviipko4oi6w5fiiLYp4oi6w5fiiLbCrCziiLYv4oanPOKBv8KvOCAxMC4rUnbilrMuLikKICAgICAg4oqZKOKKmSjiipnDl-KItiniiLYp4oi2CiAgICAgIOKKmSjiipko4o2aWzAgMV3iiqHiipkn4o2J4oqfwqw9MMOXMC4pLiniiLYKICAgICAgW-KKmeKKmeKKmeKImF3iiKniiKnijYkKICAgICkKICAgIOKOiz0wL-KGpS_ihqc9MMOXMOKNieKKouKNmOKNiS4KICApbWQKKQoK4oavW8KvMSAzXVvijaUuLTFzbV3iiqAo4oqC4oi2MOKKguKItinih6FpaOKHoWl3CitwesOXcGR1duKNmOKNiQorw5dwZHV2LTAuNVJ2IOKWsy4K4oqZLS7ijZjijYnihq_iiLZjY-KGuzHilrMuCuKKmS7iipko4oi24oav4oi2MeKWsy4pCgpS4o2JW-KKmeKKmeKKmeKImF3iiKniiKnijYkKCjs7L-KImOKHjOKNmOKNiQriiKnijYkK4oiaw7fiiLYvK-KItuKnuy7ihq9bc20gaWggaXcgM13ijYkgw5dCZ2QKCuKNnOKNmOKNieKJoSjijYnilr3ihq_ip7ss4oqZJ-KNieKWveKItuKGr-KItizip7ssMzAp) posted [by Bren077s on the discord](https://discord.com/channels/1156339038748413952/1156339039411122229/1159750150462373888).

The link is very long and, I quote:

> Had to trim some features and all comments to make the url small enough for discord to accept it.

You can see there are a few repeated glyph pairs, 11 time `⊙(` or 7 times `+×` for example. Binding names are also repeated quite often, so simple dictionary approaches to reduce byte-count per symbol should be quite effective, as you said.

**Comment by bhansconnect** [comment]
I did some local testing of compression (`gzip (lz77)`, `b2zip (lzw)`, `xz (lzma)`, `zstd`, `brotli`) on the lastest version of my ray tracer source. All algorithms and compression levels performed about the same. Compression on my ray tracer varied from `1.79x` to `2.06x`.

The best compressor at min compression level was `b2zip (lzw)` with a `1.97x`. The best compressor at standard compression level(6) was `gzip` with a `2.01x`. The best compressor at max compression level was `brotli` with a `2.06x`.

I then did the exact same test again, but removed the comments and most of the extra empty lines. So overall, removed some redundancy and english text. Compression varied from `1.67x` to `1.95x`. 

The best compressor at min compression level was `b2zip (lzw)` with a `1.67x`. The best compressor at standard compression level(6) was `gzip` with a `1.92x`. The best compressor at max compression level was `brotli` with a `1.95x`. 

Overall, it feels that exact compression algorithm does not matter _too_ much. In general, we may be able to get a 1.5x to 2x ish size reduction of larger text.

**Comment by goyalyashpal** [comment]
context: 
+ "ascii uiua": uiua with keyword names (ascii),
+ "glyphed uiua": uiua with keyword glyphs (unicode 4-byte?!)

consider these:
1. unicode takes 4 times as much as ascii for single character (right?)
2. mostly only ~70 (= 26 + 10 + 18 + (10 ± 5)) chars used in ascii-uiua; so, more repetition, higher character frequency, more compressible
3. future optimisation scope: compresssion-targetted formatter (#60) to output minimal-length ascii-name;  
4. whereas glyphed-uiua's set of possible characters would only expand

:. did you consider testing compression on ascii-uiua & comparing it with compression results on glyphed-uiua??

i am interested to see if in case of compressong ascii-uiua
- _increase in size_ by ascii-names belng multi-character

would be compensated by;

- _reduction in size & complexity_ due to points 1, 2, 3 above & use of single charset

**Comment by goyalyashpal** [comment]
> 3\. future optimisation scope: compresssion-targetted formatter ([a way to convert glyphs back into name #60](https://github.com/uiua-lang/uiua/issues/60)) to output "minimal-length unambiguous head" of ascii-name/symbol

i'd like to expand on this:
* 6 ascii-symbols (verbatim) + 2 glyphs: 50%
`` %*!<=>` `` `id` `pi`,
* various minimal-unambiguous heads are of length 3: `id not 

```# id pi
# not abs sqr sin
# mod pow log min max
# len rev box sel rot
# win mem rep dip gap
# inv try tau eta inf

# ind row dis tab 

# flo cei rou ata sha
# fir des bit tra ris fal
# cla ded unb mat cou joi
# pic tak dro kee fol eac
# cro gro par bot bra for
# und lev fil ass spa wai
# bre rec```

**Comment by iFreilicht** [comment]
@goyalyashpal 

> unicode takes 4 times as much as ascii for single character (right?)

The prevalent encoding these days is UTF-8, which is a variable-length encoding. In this encoding, a single codepoint can be up to 4 bytes long, but for the majority this is not the case. Most glyphs in Uiua are between code points U+0800 and U+FFFF, so they take exactly 3 bytes to encode.

**Comment by goyalyashpal** [comment]
> Most glyphs in Uiua are between code points U+0800 and U+FFFF

a more "strict" or tight range (for now at least) seems to be U+2190 to U+23FF i.e. "Arrows", "Mathematical Operators", "Miscellanious Technocal"

**Comment by JobLeonard** [comment]
Ok, I really appreciate the effort and how everyone is thinking about this, but this has basically been solved by people smarter than us a couple of decades ago :sweat_smile:.

To explain why this isn't going to be an issue basically requires a partial crash course in the essence behind the [LZ78 family](https://en.wikipedia.org/wiki/LZ77_and_LZ78) of compressors, please bear with me (:sweat_smile:, again).

First a crucial mathematical insight: to write down a (positive non-zero integer) number `n` in binary you only need `min(log2(n)) + 1` bits:

| number (base ten) | number (binary) |
|---|---|
| 0 | 0 |
| 1 | 1 |
| 2 | 10 |
| 3 | 11 |
| 4 | 100 |
| 7 | 111 |
| 8 | 1000 |
| 15 | 1111 |
| 16 | 10000 |
| 31 | 11111 |
| 32 | 100000 |
| ... | ... |

(Tangent: the log-scaling behavior is a result of positional notation and true for *any* base (yes, that includes [negative bases](https://www.youtube.com/watch?v=GWA_NraxOUw)))

So when we know the difference between the minimum and maximum value in a list of nrs, we can minimize how much bits we need to store them. Example: if all values are integers between [0, 255], we only need 8 bits to store per number. You probably regularly do this kind of optimization in your programs yourself. (advanced trick: when the number range isn't a neat power of two, you can actually use encodings like [phase-in codes](https://hbfs.wordpress.com/2008/09/02/phase-in-codes/) to use close to `log2(n)` bits for a uniform distribution of numbers (see also [here](https://observablehq.com/@jobleonard/number-encodings-as-trees) for an attempt at explaining of phase-in codes by me))

Look closely at *any* (lossless) compression scheme out there, and you will realize that this is actually a crucial implicit building block in all of them. It always boils down to "how can we map the patterns in this data to number representations that give us that sweet, sweet log(n) scaling behavior". Weirdly enough almost no data compression book bothers to mention that. (Tangent: it might be because [Arabic numerals](https://en.wikipedia.org/wiki/Arabic_numerals) are positional notation base 10. So basically every literate person "knows" the most fundamental lossless data compression method without realizing it, and maybe that's why it's taken for granted)

Now to turn this insight into a data compression scheme.

One approach is to create a dictionary (really just a look-up table) that only contains known characters in our input string. [Bren077's raytracer](https://www.uiua.org/pad?src=YXIg4oaQIMO3OSAxNgppdyDihpAgNTAKdmgg4oaQIDIKCm1kIOKGkCAxMApzbSDihpAgMjAKCmNjIOKGkCBbMCAwIDBdCgpjIOKGkCBbWzAgMCDCrzFdIFswIMKvMTAwLjUgwq8xXV0KciDihpAgWzAuNSAxMDBdCm1jIOKGkCBbWzAuNyAwLjMgMC4zXSBbMC44IDAuOCAwXV0KCmloIOKGkCDihqUx4oyKw7dhciBpdwp2dyDihpAgw5d2aCDDt2loIGl3Cgp2dSDihpAgW3Z3IDAgMF0KdnYg4oaQIFswIMKvdmggMF0KCnBkdSDihpAgw7dpdyB2dQpwZHYg4oaQIMO3aWggdnYKcGR1diDihpAgK3BkdSBwZHYKCnVsYyDihpAgLcO3MnZ1IC3DtzJ2diAtWzAgMCAxXSBjYwpweiDihpAgK8OXMC41cGR1diB1bGMKClJ2IOKGkCDihq_iiLZb4o2l4pqCXS_Dly4KCm5hbiDihpAgw7cwIDAKQmdkIOKGkCAr4o2aWzAg4oieXcOXWzEgMSAxXS3iiLYx4oi24o2aWzAg4oieXcOXWzAuNSAwLjcgMV0uw5cwLjUrMeKKoTHiiLonw7fiiLbiiLbiiJovK8OXLi4KClIg4oaQICgKICDijaUoCiAgICDijZzijZjijYkofDEKICAgICAg4oip4oip4o2JL-KImOKHjAogICAgICDiiLonLyvDlyws4oqZ4oi24oi6LWMuCiAgICAgIOKKmSjiiLrDl-KKmSguLyvDly4uKS3Dly5y4omhLyvDly4pCiAgICAgIOKImi3iiLbDly4s4oi2CiAgICAgIOKIuifDt-KItuKGp-KIqSgr4oiawq88MC4wMDEuKeKKgyst4oqZwq8KICAgICAgK8OX4qe7Y8KsPTDDlzAs4oqZL-KGp-KNmjEn4oqi4oyC4o2JLgogICAgICDiipkoLiviiLrDl-KItikKICAgICAg4oqZLeKItuKNmOKNieKNmlswIOKInl3iiqEs4oqCY1tuYW4gbmFuIG5hbl0KICAgICAg4oqZKOKIuifDt-KItuKItiniiLbijZpbMCDiiJ5d4oqhLOKKgnIgbmFuCiAgICAgIOKNmOKNieKNmlswIOKInl3iiqHiiLbiioJtY1sxIDEgMV0KICAgICAg4oqZKCviipko4oi6w5fiiLYp4oi6w5fiiLbCrCziiLYv4oanPOKBv8KvOCAxMC4rUnbilrMuLikKICAgICAg4oqZKOKKmSjiipnDl-KItiniiLYp4oi2CiAgICAgIOKKmSjiipko4o2aWzAgMV3iiqHiipkn4o2J4oqfwqw9MMOXMC4pLiniiLYKICAgICAgW-KKmeKKmeKKmeKImF3iiKniiKnijYkKICAgICkKICAgIOKOiz0wL-KGpS_ihqc9MMOXMOKNieKKouKNmOKNiS4KICApbWQKKQoK4oavW8KvMSAzXVvijaUuLTFzbV3iiqAo4oqC4oi2MOKKguKItinih6FpaOKHoWl3CitwesOXcGR1duKNmOKNiQorw5dwZHV2LTAuNVJ2IOKWsy4K4oqZLS7ijZjijYnihq_iiLZjY-KGuzHilrMuCuKKmS7iipko4oi24oav4oi2MeKWsy4pCgpS4o2JW-KKmeKKmeKKmeKImF3iiKniiKnijYkKCjs7L-KImOKHjOKNmOKNiQriiKnijYkK4oiaw7fiiLYvK-KItuKnuy7ihq9bc20gaWggaXcgM13ijYkgw5dCZ2QKCuKNnOKNmOKNieKJoSjijYnilr3ihq_ip7ss4oqZJ-KNieKWveKItuKGr-KItizip7ssMzAp) has only 81 unique characters, for example. With a dictionary containing only those letters we could compress the string by storing the indices for each letter in it, which needs roughly 6.4 bits per character with phase-in codes (ignoring actual distribution of letters).

You might ask "ok, but then we need to send over the dictionary, which also takes up space, no?"

Here is how to work around that: start with a dictionary with one entry: a special `new character` escape token. If we are decoding our compressed bits and encounter it, we know that we have to read the next `n` bits as a character literal (`n` depends on character encoding and character) and add the character to reconstructed string and our dictionary. After that we can use its dictionary entry. So on top of sending over a literal once, we only pay an overhead cost of one escape token.

The LZ78 algorithm then expands on this concept by not just limit itself to single characters, but also having a way to build a dictionary of longer substrings from previously seen text, based on the assumption it will likely encounter them again. This is already a mountain of text so I'm going to skip explaining the full algorithm for that.

What's more important here is the uiua glyphs. There are currently about 80 unique uiua glyphs, not including the ASCII ones). We could pre-load all of them in the dictionary, but most snippets use only a handful of those - we'd waste precious bits encoding "index `i` out of 80" instead of "index `i` out of [tiny handful]". So instead we can create a *second* dedicated uiua glyph dictionary, that we can access with a second escape code: `new uiua glyph`. Then that would have an overhead of about 7 bits per newly encountered glyph in the input plus escape code. This is much less than the 24 or 32 bytes for the full UTF literal. And after that it would only need as much bits as the main dictionary size.

As long as we make this glyph dictionary an append-only one as new glyphs are added (meaning any new glyphs added to the language are added at the end, and if they are removed from the language they stay in it the list), we can both update this table for new uiua verions while keeping the compressions scheme backwards-compatible to the previous version: just start the compressed bitstream with a nr encoding the uiua glyph dictionary size (which is effectively the compression scheme's semver). Even if we'd cycle through so many glyph shapes the list is 255 glyphs long, that still just requires 8 bits to load a uiua glyph not previously encountered (because of that sweet, sweet log(n) scaling behavior).

So yeah, we're probably fine there.

Phew, that was a lot. Hope it was clear enough to follow.
