### ISSUE TITLE
why not convert "ascii" having glyphs names too?

### ISSUE THREAD

**Issue by goyalyashpal** [uiua-lang/uiua#84]
i had seen that right when that commit was made, but i resisted the temptation to ask immediately
https://github.com/uiua-lang/uiua/commit/07378ef652bc86a99f663a400f1856e4aa06adaf

but now i can't stop 😅 
so, why this exception??

https://github.com/uiua-lang/uiua/blob/07378ef652bc86a99f663a400f1856e4aa06adaf/site/src/tutorial.rs#L170-L172

**Comment by kaikalii** [comment]
It is to have fewer reserved lowercase words.

**Comment by goyalyashpal** [comment]
> It is to have fewer reserved lowercase words.

i agree - but it confused me twice when i was starting: once for "bind", and then again with "negate"

**Comment by goyalyashpal** [comment]
added in https://github.com/uiua-lang/uiua/commit/abb7f3f6a90d9b53e5d832c2af15cdfffdd9366c
