### ISSUE TITLE
thoughts on rotate stack?

### ISSUE THREAD

**Issue by goyalyashpal** [uiua-lang/uiua#85]
* i am not saying to include this feature, 
* but i often wonder what would be the pros and cons of rotate stack?
* note: it's very limited in scope, and should not be confused with restack
* but yeah, the problem with readability may still be there if implemented without much thought

i have seen it in `dirs` gnu-utils group:

```console
$ pushd --help | grep -EniA 1 "(\+|-)n"
1:pushd: pushd [-n] [+N | -N | dir]
2-    Add directories to stack.
--
9:      -n      Suppresses the normal change of directory when adding
10-             directories to the stack, so only the stack is manipulated.
--
13:      +N     Rotates the stack so that the Nth directory (counting
14-             from the left of the list shown by `dirs', starting with
--
17:      -N     Rotates the stack so that the Nth directory (counting
18-             from the right of the list shown by `dirs', starting with

$ popd --help | grep -EniA 1 "(\+|-)n"
$ help dirs | grep -EniA 1 "(\+|-)n"```

**Comment by kaikalii** [comment]
Uiua previously had `roll` and `unroll` which rotated the top 3 stack elements.
I found this very difficult to reason about, so I removed them.
In general, I dislike operations that change the order of values on the stack.
This is why `restack` is also gone now.

**Comment by goyalyashpal** [comment]
yep, i also thought about same parallels - but how rotate differs from all these 3 is that concept of rotate doesn't feel super arbitrary.
