### ISSUE TITLE
[meta] add the "why" in commit body too

### ISSUE THREAD

**Issue by goyalyashpal** [uiua-lang/uiua#86]
* add the "why" in commit body too: even 1-2 sentences will suffice. 
* it will function as dod (defense of design) itself 😃 ; and hence will super reduce any nagging annoying questions
* also, don't ever post only links there, make sure the crux of the reasoning is understandable right there in the plain text commit body 😃 
* this will also act as a last chance to think about if the change/design is good

https://github.com/uiua-lang/uiua/blob/eff92d4a3f6384ec4922901f588b276ce00a4598/site/src/other.rs#L17-L19

examples:

* https://github.com/uiua-lang/uiua/commit/81afa83d1c55e05b39033a60b6b9071e9d0f008d & https://github.com/uiua-lang/uiua/commit/a117396ac23d0807db14eaa42bf40e43db76e019: _"change dip's glyph"_ (`→` to `⊙`)
the arrow felt super apt: it moves the current position of the stack one position towards right for the next operation.
* https://github.com/uiua-lang/uiua/commit/07378ef652bc86a99f663a400f1856e4aa06adaf ([\#84](https://github.com/uiua-lang/uiua/issues/84)): _"formatting of ascii glyph functions"_
* https://github.com/uiua-lang/uiua/commit/27bcc47a67b2b758e334ddd218a141b564ed8ed7 https://github.com/uiua-lang/uiua/commit/01df5573f74440d0b7fd18df612f8a35439f0667: _"call it [share] lives"_ then reversion: _"rename lives to share"_

**Comment by iFreilicht** [comment]
The currently frequent changes are motivated by the attempt to make working with multiple values on the stack easier. The newest iteration, which is what you're seeing with dip here, is [planet notation](https://www.uiua.org/docs/advancedstack).

In general, the language evolves very quickly right now, and the docs are kept in sync to serve as the dod, but I don't have a strong opinion on this.

**Comment by kaikalii** [comment]
This is not how I use commits.
I have been putting brief explanations in the changelogs.

**Comment by goyalyashpal** [comment]
> in the changelogs

https://github.com/uiua-lang/uiua/blob/main/changelog.md

'kayh 👍

**Comment by goyalyashpal** [comment]
yeah, thats much much better

**Comment by goyalyashpal** [comment]
the downside of manual changelog is that its disconnected with commits (or would require more additonal efforts)

not to mention the chance of missing smth

----
if the commit had body, 

then i suppose u could use commit-changelog to _automatically_ generate the changelog from commits-body & just tweak it from there.

Refer:
* Changelog auto-generated by [Release Changelog Builder Action (Mike Penz)](https://github.com/mikepenz/release-changelog-builder-action).
* Source: https://github.com/cyb3rko/pincredible/releases/tag/v0.5.0
