### ISSUE TITLE
Wrong stack signature inferred when `pick`ing function from array

### ISSUE THREAD

**Issue by jshholland** [uiua-lang/uiua#89]
The following code behaves as expected:
```
choose ← ! ⊡∶(|1 +1)_(|1 ×4)_(|1 ÷3) .

choose 0
choose 1
choose 2
```
Output with uiua from commit 5cdb0e7:
```
1
4
0.6666666666666666
```

However, if I add a stack signature (or try passing `choose` to a modifier that expects a single-output function, like `each`), then it fails:
```
Error: Function signature mismatch: declared |1.1 but inferred |1.2
   ╭─[..../sig.ua:1:10]
 1 │ choose ← |1 ! ⊡∶(|1 +1)_(|1 ×4)_(|1 ÷3) .
   │          ──  
───╯
```

Note I was as explicit as possible giving signatures to the functions in the array.

**Comment by kaikalii** [comment]
This is a problem with the checkability of explicit calls.
Call is |1.1 for its use case as an unboxing function.
But weird stuff happens in cases like this.
I'll have to think about how to solve this.
Sorry for the inconvenience!

**Comment by kaikalii** [comment]
I have put a special case in the signature checker for this pattern.
It is available on `main`, and will be available elsewhere in the next version.

**Comment by kaikalii** [comment]
The fix for this is live on both native and web!
