### ISSUE TITLE
Proper Releases

### ISSUE THREAD

**Issue by cafkafk** [uiua-lang/uiua#90]
Would uiua-lang consider making "proper" releases for their versions. Right now, it seems they are just tagged. This makes it hard for users to discover, and makes my life as a nixpkgs maintainer a little harder, since I won't see in my feed that there's a new release.

**Comment by kaikalii** [comment]
Sure.
For the next one, I will make a proper release.

**Comment by cafkafk** [comment]
Awesome, thanks!

**Comment by kaikalii** [comment]
[Behold](https://github.com/uiua-lang/uiua/releases)

**Comment by cafkafk** [comment]
I came, I saw, I updated https://github.com/NixOS/nixpkgs/pull/259677
